use crate::compiler::ast_generator::{
    collect_collision_checks, collect_tilemap_assets, AabbCollisionCheck, AstNode, AstOutput,
    SpriteAsset, TilemapAsset,
};

#[derive(Debug)]
pub struct EmitOutput {
    pub main_c: String,
    pub resources_res: String,
}

pub fn emit_sgdk(ast: &AstOutput, project_name: &str) -> EmitOutput {
    EmitOutput {
        main_c: build_main_c(ast, project_name),
        resources_res: build_resources_res(ast),
    }
}

fn build_main_c(ast: &AstOutput, project_name: &str) -> String {
    let mut out = String::new();
    let collision_checks = collect_collision_checks(ast);
    let tilemap_assets = collect_tilemap_assets(ast);
    let include_resources = !ast.sprite_assets.is_empty() || !tilemap_assets.is_empty();

    out.push_str(&format!(
        "// Generated by RetroDev Studio - DO NOT EDIT\n\
         // Project: {}\n\n\
         #include <genesis.h>\n",
        project_name
    ));
    if include_resources {
        out.push_str("#include \"resources.h\"\n");
    }
    out.push('\n');

    for asset in &ast.sprite_assets {
        out.push_str(&format!("static Sprite* spr_{};\n", asset.resource_name));
    }
    if !ast.sprite_assets.is_empty() {
        out.push('\n');
    }
    if !collision_checks.is_empty() {
        out.push_str(render_aabb_helper());
        out.push('\n');
    }

    out.push_str("int main() {\n");
    if let Some((plane_width, plane_height)) = plane_size_for_tilemaps(&tilemap_assets) {
        out.push_str(&format!(
            "    VDP_setPlaneSize({}, {}, TRUE);\n",
            plane_width, plane_height
        ));
    }

    let mut tilemap_draw_index = 0usize;
    for node in &ast.nodes {
        match node {
            AstNode::SpriteSystemInit => {
                out.push_str("    SPR_init();\n");
            }
            AstNode::LoadTilemap {
                resource_name,
                map_width,
                map_height,
                ..
            } => {
                out.push_str(&format!(
                    "    // Load tilemap: {} ({}x{} tiles)\n",
                    resource_name, map_width, map_height
                ));
            }
            AstNode::LoadSpritesheet {
                resource_name,
                frame_width,
                frame_height,
                palette_slot,
                ..
            } => {
                out.push_str(&format!(
                    "    // Load spritesheet: {} ({}x{} px, palette {})\n",
                    resource_name, frame_width, frame_height, palette_slot
                ));
            }
            AstNode::SpawnSprite {
                var_name,
                resource_name,
                x,
                y,
                priority_high,
            } => {
                let palette = ast
                    .sprite_assets
                    .iter()
                    .find(|asset| asset.resource_name == *resource_name)
                    .map(|asset| palette_const(asset.palette_slot))
                    .unwrap_or_else(|| "PAL0".to_string());
                let priority = if *priority_high { "TRUE" } else { "FALSE" };

                out.push_str(&format!(
                    "    {} = SPR_addSprite(&{}, {}, {}, TILE_ATTR({}, 1, FALSE, {}));\n",
                    var_name, resource_name, x, y, palette, priority
                ));
            }
            AstNode::DrawTilemap {
                resource_name,
                x,
                y,
                scroll_x,
                scroll_y,
            } => {
                let plane = tilemap_plane(tilemap_draw_index);
                let base_tile = tilemap_base_expression(resource_name, &tilemap_assets);
                out.push_str(&format!(
                    "    VDP_drawImageEx({}, &{}, TILE_ATTR_FULL(PAL0, FALSE, FALSE, FALSE, {}), {}, {}, TRUE, TRUE);\n",
                    plane,
                    resource_name,
                    base_tile,
                    (*x).max(0) / 8,
                    (*y).max(0) / 8
                ));
                if *scroll_x != 0 {
                    out.push_str(&format!(
                        "    VDP_setHorizontalScroll({}, {});\n",
                        plane, scroll_x
                    ));
                }
                if *scroll_y != 0 {
                    out.push_str(&format!(
                        "    VDP_setVerticalScroll({}, {});\n",
                        plane, scroll_y
                    ));
                }
                tilemap_draw_index += 1;
            }
            AstNode::ReadInputDevice { device, state_var } => {
                out.push_str(&format!(
                    "        u16 {} = JOY_readJoypad({});\n",
                    state_var,
                    sgdk_joypad_port(device)
                ));
            }
            AstNode::MapInputAction {
                result_name,
                entity_id,
                action_name,
                state_var,
                button,
            } => {
                render_input_binding(
                    &mut out,
                    result_name,
                    entity_id,
                    action_name,
                    state_var,
                    button,
                );
            }
            AstNode::CheckCollisionAabb {
                result_name,
                left,
                right,
            } => {
                render_collision_check(
                    &mut out,
                    &AabbCollisionCheck {
                        result_name: result_name.clone(),
                        left: left.clone(),
                        right: right.clone(),
                    },
                );
            }
            AstNode::SetAnimation {
                var_name,
                anim_index,
                looping,
                ..
            } => {
                out.push_str(&format!("    SPR_setAnim({}, {});\n", var_name, anim_index));
                if !looping {
                    out.push_str(&format!("    SPR_setAnimationLoop({}, FALSE);\n", var_name));
                }
            }
            AstNode::DrawText {
                x,
                y,
                text,
                palette_slot,
            } => {
                let escaped = text.replace('"', "\\\"");
                out.push_str(&format!(
                    "    VDP_drawText(\"{}\", {}, {});\n",
                    escaped, x, y
                ));
                if *palette_slot > 0 {
                    out.push_str(&format!("    VDP_setTextPalette({});\n", palette_slot));
                }
            }
            AstNode::GameLoopBegin => {
                out.push_str("\n    while (TRUE) {\n");
            }
            AstNode::SpriteUpdate => {
                out.push_str("        SPR_update();\n");
            }
            AstNode::VSync => {
                out.push_str("        SYS_doVBlankProcess();\n");
            }
            AstNode::GameLoopEnd => {
                out.push_str("    }\n");
            }
        }
    }

    out.push_str("\n    return 0;\n}\n");
    out
}

fn build_resources_res(ast: &AstOutput) -> String {
    let mut out = String::new();
    out.push_str("// Generated by RetroDev Studio - DO NOT EDIT\n\n");

    for asset in collect_tilemap_assets(ast) {
        out.push_str(&format!(
            "IMAGE {} \"{}\" NONE\n",
            asset.resource_name,
            tilemap_resource_path(&asset.asset_path),
        ));
    }

    for asset in &ast.sprite_assets {
        out.push_str(&format!(
            "SPRITE {} \"{}\" {} {} NONE {}\n",
            asset.resource_name,
            asset.asset_path,
            asset.frame_width / 8,
            asset.frame_height / 8,
            resource_animation_time(asset),
        ));
    }

    out
}

fn resource_animation_time(asset: &SpriteAsset) -> u32 {
    asset
        .default_animation
        .as_ref()
        .map(|animation| animation.frame_time)
        .unwrap_or(4)
}

fn render_aabb_helper() -> &'static str {
    "static u8 retro_aabb_intersects(s16 left_x, s16 left_y, u16 left_w, u16 left_h, s16 right_x, s16 right_y, u16 right_w, u16 right_h)\n\
{\n\
    return left_x < (right_x + (s16)right_w)\n\
        && (left_x + (s16)left_w) > right_x\n\
        && left_y < (right_y + (s16)right_h)\n\
        && (left_y + (s16)left_h) > right_y;\n\
}\n"
}

fn render_collision_check(out: &mut String, check: &AabbCollisionCheck) {
    out.push_str(&format!(
        "        u8 {result_name} = retro_aabb_intersects({left_x}, {left_y}, {left_width}, {left_height}, {right_x}, {right_y}, {right_width}, {right_height});\n",
        result_name = check.result_name,
        left_x = check.left.x,
        left_y = check.left.y,
        left_width = check.left.width,
        left_height = check.left.height,
        right_x = check.right.x,
        right_y = check.right.y,
        right_width = check.right.width,
        right_height = check.right.height
    ));
    out.push_str(&format!(
        "        if ({}) {{\n            // Collision: {} <-> {}\n        }}\n",
        check.result_name, check.left.entity_id, check.right.entity_id
    ));
}

fn render_input_binding(
    out: &mut String,
    result_name: &str,
    entity_id: &str,
    action_name: &str,
    state_var: &str,
    button: &str,
) {
    let Some(button_mask) = sgdk_button_mask(button) else {
        out.push_str(&format!(
            "        // Unsupported input mapping on SGDK: {}.{} -> {}\n",
            entity_id, action_name, button
        ));
        return;
    };

    out.push_str(&format!(
        "        u16 {result_name} = {state_var} & {button_mask};\n",
        result_name = result_name,
        state_var = state_var,
        button_mask = button_mask
    ));
    out.push_str(&format!(
        "        if ({}) {{\n            // Input: {}.{}\n        }}\n",
        result_name, entity_id, action_name
    ));
}

fn sgdk_joypad_port(device: &str) -> &'static str {
    match device {
        "joypad_2" => "JOY_2",
        "joypad_3" => "JOY_3",
        "joypad_4" => "JOY_4",
        _ => "JOY_1",
    }
}

fn sgdk_button_mask(button: &str) -> Option<&'static str> {
    match button {
        "DPAD_UP" => Some("BUTTON_UP"),
        "DPAD_DOWN" => Some("BUTTON_DOWN"),
        "DPAD_LEFT" => Some("BUTTON_LEFT"),
        "DPAD_RIGHT" => Some("BUTTON_RIGHT"),
        "BUTTON_A" => Some("BUTTON_A"),
        "BUTTON_B" => Some("BUTTON_B"),
        "BUTTON_C" => Some("BUTTON_C"),
        "BUTTON_X" => Some("BUTTON_X"),
        "BUTTON_Y" => Some("BUTTON_Y"),
        "BUTTON_Z" => Some("BUTTON_Z"),
        "START" => Some("BUTTON_START"),
        _ => None,
    }
}

fn plane_size_for_tilemaps(tilemap_assets: &[TilemapAsset]) -> Option<(u16, u16)> {
    if tilemap_assets.is_empty() {
        return None;
    }

    let max_width = tilemap_assets
        .iter()
        .map(|asset| if asset.map_width > 32 { 64 } else { 32 })
        .max()
        .unwrap_or(32) as u16;
    let max_height = tilemap_assets
        .iter()
        .map(|asset| if asset.map_height > 32 { 64 } else { 32 })
        .max()
        .unwrap_or(32) as u16;

    Some((max_width, max_height))
}

fn tilemap_plane(index: usize) -> &'static str {
    match index {
        0 => "BG_B",
        1 => "BG_A",
        _ => "WINDOW",
    }
}

fn tilemap_base_expression(resource_name: &str, tilemap_assets: &[TilemapAsset]) -> String {
    let mut terms = vec!["TILE_USER_INDEX".to_string()];
    for asset in tilemap_assets {
        if asset.resource_name == resource_name {
            break;
        }
        terms.push(format!("{}.tileset->numTile", asset.resource_name));
    }
    terms.join(" + ")
}

fn tilemap_resource_path(asset_path: &str) -> String {
    let path = std::path::Path::new(asset_path);
    normalize_path(&path.with_extension("bmp").to_string_lossy())
}

fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
}

fn palette_const(slot: u8) -> String {
    match slot {
        0 => "PAL0".to_string(),
        1 => "PAL1".to_string(),
        2 => "PAL2".to_string(),
        3 => "PAL3".to_string(),
        _ => "PAL0".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::ast_generator::SpriteAnimation;

    fn sprite_asset_with_animation(frame_time: u32, looping: bool) -> SpriteAsset {
        SpriteAsset {
            resource_name: "hero".to_string(),
            asset_path: "assets/sprites/hero.png".to_string(),
            frame_width: 16,
            frame_height: 16,
            palette_slot: 1,
            animation_count: 4,
            default_animation: Some(SpriteAnimation {
                name: "walk".to_string(),
                frames: vec![0, 1, 2, 3],
                frame_time,
                looping,
            }),
        }
    }

    #[test]
    fn resources_res_uses_animation_timing_from_ast() {
        let ast = AstOutput {
            nodes: Vec::new(),
            sprite_assets: vec![sprite_asset_with_animation(6, true)],
        };

        let output = emit_sgdk(&ast, "Timing Demo");

        assert!(output
            .resources_res
            .contains("SPRITE hero \"assets/sprites/hero.png\" 2 2 NONE 6"));
    }

    #[test]
    fn main_c_disables_loop_for_non_looping_animation() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::SpriteSystemInit,
                AstNode::SpawnSprite {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    x: 16,
                    y: 24,
                    priority_high: true,
                },
                AstNode::SetAnimation {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    anim_index: 0,
                    frame_time: 6,
                    frames: vec![0, 1, 2, 3],
                    looping: false,
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: vec![sprite_asset_with_animation(6, false)],
        };

        let output = emit_sgdk(&ast, "Timing Demo");

        assert!(output.main_c.contains("SPR_setAnim(spr_hero, 0);"));
        assert!(output
            .main_c
            .contains("SPR_setAnimationLoop(spr_hero, FALSE);"));
    }

    #[test]
    fn resources_res_emits_image_resource_for_tilemap_assets() {
        let ast = AstOutput {
            nodes: vec![AstNode::LoadTilemap {
                resource_name: "background_tilemap".to_string(),
                asset_path: "assets/tilesets/level.ppm".to_string(),
                map_width: 32,
                map_height: 32,
            }],
            sprite_assets: Vec::new(),
        };

        let output = emit_sgdk(&ast, "Tilemap Demo");

        assert!(output
            .resources_res
            .contains("IMAGE background_tilemap \"assets/tilesets/level.bmp\" NONE"));
    }

    #[test]
    fn main_c_draws_tilemap_with_scroll() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::LoadTilemap {
                    resource_name: "background_tilemap".to_string(),
                    asset_path: "assets/tilesets/level.ppm".to_string(),
                    map_width: 64,
                    map_height: 32,
                },
                AstNode::DrawTilemap {
                    resource_name: "background_tilemap".to_string(),
                    x: 16,
                    y: 24,
                    scroll_x: 8,
                    scroll_y: 4,
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
        };

        let output = emit_sgdk(&ast, "Tilemap Demo");

        assert!(output.main_c.contains("VDP_setPlaneSize(64, 32, TRUE);"));
        assert!(output.main_c.contains(
            "VDP_drawImageEx(BG_B, &background_tilemap, TILE_ATTR_FULL(PAL0, FALSE, FALSE, FALSE, TILE_USER_INDEX), 2, 3, TRUE, TRUE);"
        ));
        assert!(output.main_c.contains("VDP_setHorizontalScroll(BG_B, 8);"));
        assert!(output.main_c.contains("VDP_setVerticalScroll(BG_B, 4);"));
    }

    #[test]
    fn main_c_emits_manual_aabb_collision_checks() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::CheckCollisionAabb {
                    result_name: "collision_player_badnik".to_string(),
                    left: crate::compiler::ast_generator::CollisionBox {
                        entity_id: "player".to_string(),
                        x: 18,
                        y: 28,
                        width: 16,
                        height: 24,
                    },
                    right: crate::compiler::ast_generator::CollisionBox {
                        entity_id: "badnik".to_string(),
                        x: 40,
                        y: 28,
                        width: 24,
                        height: 24,
                    },
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
        };

        let output = emit_sgdk(&ast, "Collision Demo");

        assert!(output.main_c.contains("static u8 retro_aabb_intersects("));
        assert!(output.main_c.contains(
            "u8 collision_player_badnik = retro_aabb_intersects(18, 28, 16, 24, 40, 28, 24, 24);"
        ));
        assert!(output
            .main_c
            .contains("// Collision: player <-> badnik"));
    }

    #[test]
    fn main_c_reads_sgdk_input_mappings() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::ReadInputDevice {
                    device: "joypad_1".to_string(),
                    state_var: "joypad_1_state".to_string(),
                },
                AstNode::MapInputAction {
                    result_name: "input_player_move_left".to_string(),
                    entity_id: "player".to_string(),
                    action_name: "move_left".to_string(),
                    state_var: "joypad_1_state".to_string(),
                    button: "DPAD_LEFT".to_string(),
                },
                AstNode::MapInputAction {
                    result_name: "input_player_jump".to_string(),
                    entity_id: "player".to_string(),
                    action_name: "jump".to_string(),
                    state_var: "joypad_1_state".to_string(),
                    button: "BUTTON_A".to_string(),
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
        };

        let output = emit_sgdk(&ast, "Input Demo");

        assert!(output
            .main_c
            .contains("u16 joypad_1_state = JOY_readJoypad(JOY_1);"));
        assert!(output
            .main_c
            .contains("u16 input_player_move_left = joypad_1_state & BUTTON_LEFT;"));
        assert!(output
            .main_c
            .contains("u16 input_player_jump = joypad_1_state & BUTTON_A;"));
        assert!(output.main_c.contains("// Input: player.move_left"));
        assert!(output.main_c.contains("// Input: player.jump"));
    }
}
