use crate::compiler::ast_generator::{AstNode, AstOutput};

/// Resultado da emissão: código C + arquivo de recursos SGDK
#[derive(Debug)]
pub struct EmitOutput {
    pub main_c: String,
    pub resources_res: String,
}

/// Traduz o AST para código C compatível com SGDK (Mega Drive).
pub fn emit_sgdk(ast: &AstOutput, project_name: &str) -> EmitOutput {
    let main_c = build_main_c(ast, project_name);
    let resources_res = build_resources_res(ast);
    EmitOutput { main_c, resources_res }
}

// ── main.c ────────────────────────────────────────────────────────────────────

fn build_main_c(ast: &AstOutput, project_name: &str) -> String {
    let mut out = String::new();
    let include_resources = !ast.sprite_assets.is_empty();

    // Header
    out.push_str(&format!(
        "// Generated by RetroDev Studio — DO NOT EDIT\n\
         // Project: {}\n\
         \n\
         #include <genesis.h>\n",
        project_name
    ));
    if include_resources {
        out.push_str("#include \"resources.h\"\n");
    }
    out.push('\n');

    // Forward declarations for sprite vars
    for asset in &ast.sprite_assets {
        out.push_str(&format!(
            "static Sprite* spr_{};\n",
            asset.resource_name
        ));
    }

    if !ast.sprite_assets.is_empty() {
        out.push('\n');
    }

    // int main()
    out.push_str("int main() {\n");

    // Body — translate AST nodes
    for node in &ast.nodes {
        match node {
            AstNode::SpriteSystemInit => {
                out.push_str("    SPR_init();\n");
            }

            AstNode::LoadSpritesheet {
                resource_name,
                frame_width,
                frame_height,
                palette_slot,
                ..
            } => {
                // SGDK: SPR_addSprite(&spritedef, x, y, TILE_ATTR(PAL0, 1, FALSE, FALSE))
                // Resource is declared in resources.res and available as extern SpriteDefinition
                out.push_str(&format!(
                    "    // Load spritesheet: {} ({}x{} px, palette {})\n",
                    resource_name, frame_width, frame_height, palette_slot
                ));
            }

            AstNode::SpawnSprite {
                var_name,
                resource_name,
                x,
                y,
                priority_high,
            } => {
                let pal = ast.sprite_assets
                    .iter()
                    .find(|a| a.resource_name == *resource_name)
                    .map(|a| palette_const(a.palette_slot))
                    .unwrap_or_else(|| "PAL0".to_string());

                let prio = if *priority_high { "TRUE" } else { "FALSE" };

                out.push_str(&format!(
                    "    {} = SPR_addSprite(&{}, {}, {}, TILE_ATTR({}, 1, FALSE, {}));\n",
                    var_name, resource_name, x, y, pal, prio
                ));
            }

            AstNode::SetAnimation { var_name, anim_index } => {
                out.push_str(&format!(
                    "    SPR_setAnim({}, {});\n",
                    var_name, anim_index
                ));
            }

            AstNode::DrawText { x, y, text, palette_slot } => {
                let escaped = text.replace('"', "\\\"");
                out.push_str(&format!(
                    "    VDP_drawText(\"{}\", {}, {});\n",
                    escaped, x, y
                ));
                // palette_slot used for color — set via VDP_setTextPalette if needed
                if *palette_slot > 0 {
                    out.push_str(&format!(
                        "    VDP_setTextPalette({});\n",
                        palette_slot
                    ));
                }
            }

            AstNode::GameLoopBegin => {
                out.push_str("\n    while (TRUE) {\n");
            }

            AstNode::SpriteUpdate => {
                out.push_str("        SPR_update();\n");
            }

            AstNode::VSync => {
                out.push_str("        SYS_doVBlankProcess();\n");
            }

            AstNode::GameLoopEnd => {
                out.push_str("    }\n");
            }
        }
    }

    out.push_str("\n    return 0;\n}\n");
    out
}

// ── resources.res ─────────────────────────────────────────────────────────────

fn build_resources_res(ast: &AstOutput) -> String {
    let mut out = String::new();
    out.push_str("// Generated by RetroDev Studio — DO NOT EDIT\n\n");

    for asset in &ast.sprite_assets {
        // SGDK resource declaration:
        // SPRITE name "path/to/asset.png" frame_w frame_h COMP speed
        let speed = 4; // default: animação a 4 frames (ajustável)
        out.push_str(&format!(
            "SPRITE {} \"{}\" {} {} NONE {}\n",
            asset.resource_name,
            asset.asset_path,
            asset.frame_width / 8,  // tiles wide
            asset.frame_height / 8, // tiles high
            speed
        ));
    }

    out
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn palette_const(slot: u8) -> String {
    match slot {
        0 => "PAL0".to_string(),
        1 => "PAL1".to_string(),
        2 => "PAL2".to_string(),
        3 => "PAL3".to_string(),
        _ => "PAL0".to_string(),
    }
}
