use crate::compiler::ast_generator::{AstNode, AstOutput};

/// Resultado da emissão PVSnesLib: código C + arquivo de recursos
#[derive(Debug)]
pub struct EmitOutput {
    pub main_c: String,
    pub resources_res: String,
}

/// Traduz o AST para código C compatível com PVSnesLib (SNES).
/// Recebe o mesmo AstOutput agnóstico gerado por ast_generator.
pub fn emit_snes(ast: &AstOutput, project_name: &str) -> EmitOutput {
    let main_c = build_main_c(ast, project_name);
    let resources_res = build_resources_res(ast);
    EmitOutput { main_c, resources_res }
}

// ── main.c ────────────────────────────────────────────────────────────────────

fn build_main_c(ast: &AstOutput, project_name: &str) -> String {
    let mut out = String::new();

    // Header PVSnesLib
    out.push_str(&format!(
        "// Generated by RetroDev Studio — DO NOT EDIT\n\
         // Project: {}\n\
         // Target: SNES (PVSnesLib)\n\
         \n\
         #include <snes.h>\n\
         #include \"resources.h\"\n\
         \n",
        project_name
    ));

    // Forward declarations for OAM sprite handles
    for asset in &ast.sprite_assets {
        out.push_str(&format!(
            "static u16 oam_{};\n",
            asset.resource_name
        ));
    }

    if !ast.sprite_assets.is_empty() {
        out.push('\n');
    }

    // int main()
    out.push_str("int main() {\n");

    for node in &ast.nodes {
        match node {
            AstNode::SpriteSystemInit => {
                // PVSnesLib: inicializa o sistema de OAM
                out.push_str("    oamInit(&oamMemory, OBJ_SIZE8_L16, false);\n");
            }

            AstNode::LoadSpritesheet {
                resource_name,
                frame_width,
                frame_height,
                palette_slot,
                ..
            } => {
                out.push_str(&format!(
                    "    // Load spritesheet: {} ({}x{} px, palette {})\n",
                    resource_name, frame_width, frame_height, palette_slot
                ));
                out.push_str(&format!(
                    "    dmaCopyVram({}_tiles, {}_TILES_ADDR, {}_tiles_size);\n",
                    resource_name, resource_name.to_uppercase(), resource_name
                ));
                out.push_str(&format!(
                    "    dmaCopyCGram({}_pal, {} * 16, {}_pal_size);\n",
                    resource_name, palette_slot, resource_name
                ));
            }

            AstNode::SpawnSprite {
                var_name,
                resource_name,
                x,
                y,
                priority_high,
            } => {
                let prio: u8 = if *priority_high { 3 } else { 0 };
                out.push_str(&format!(
                    "    oam_{} = oamSet(0, {}, {}, {}, {}, {}_TILES_INDEX, 0, OBJ_SIZE8);\n",
                    var_name, x, y, prio, prio, resource_name.to_uppercase()
                ));
            }

            AstNode::SetAnimation { var_name, anim_index } => {
                // PVSnesLib não tem API nativa de animação; insere comentário orientativo
                out.push_str(&format!(
                    "    // TODO: set animation {} for sprite oam_{} (implement manually with oamSet per frame)\n",
                    anim_index, var_name
                ));
            }

            AstNode::DrawText { x, y, text, palette_slot } => {
                let escaped = text.replace('"', "\\\"");
                out.push_str(&format!(
                    "    consoleSetTextColor({});\n",
                    palette_slot
                ));
                out.push_str("    consoleInitText(0, 16 * 2, &font_tiles, &font_pal);\n");
                out.push_str(&format!(
                    "    consoleDrawText({}, {}, \"{}\");\n",
                    x, y, escaped
                ));
            }

            AstNode::GameLoopBegin => {
                out.push_str("\n    while (true) {\n");
            }

            AstNode::SpriteUpdate => {
                out.push_str("        oamUpdate();\n");
            }

            AstNode::VSync => {
                out.push_str("        WaitForVBlank();\n");
            }

            AstNode::GameLoopEnd => {
                out.push_str("    }\n");
            }
        }
    }

    out.push_str("\n    return 0;\n}\n");
    out
}

// ── resources.res ─────────────────────────────────────────────────────────────
// PVSnesLib usa arquivo .rc (padrão grit/pcx2snes), mas mantemos .res por consistência.

fn build_resources_res(ast: &AstOutput) -> String {
    let mut out = String::new();
    out.push_str("// Generated by RetroDev Studio — DO NOT EDIT\n");
    out.push_str("// PVSnesLib resource list (grit compatible)\n\n");

    for asset in &ast.sprite_assets {
        // grit flags: 8x8 tiles, 4bpp, palette export, sprite mode
        out.push_str(&format!(
            "# {}: {} ({}x{} px)\n",
            asset.resource_name,
            asset.asset_path,
            asset.frame_width,
            asset.frame_height
        ));
        out.push_str(&format!(
            "grit {} -gt -gB4 -mR! -p -pe16 -pn {}\n\n",
            asset.asset_path,
            asset.resource_name
        ));
    }

    out
}
