use crate::compiler::ast_generator::{
    collect_bgm_tracks, collect_collision_checks, collect_logic_sound_names,
    collect_parallax_layers, collect_physics_applications, collect_raster_lines,
    collect_sfx_resources, collect_tilemap_assets, AabbCollisionCheck, AstNode, AstOutput,
    LogicBoolExpr, LogicCollisionTarget, LogicOp, LogicMathExpr, CompareOp, LogicPositionSource, LogicScript,
    ParallaxLayerConfig, PhysicsApplication, RasterLineConfig, SpriteAsset, TilemapAsset,
};

#[derive(Debug)]
pub struct EmitOutput {
    pub main_c: String,
    pub resources_res: String,
}

#[derive(Debug, Clone, Copy)]
struct SpriteSizeConfig {
    oam_size: &'static str,
    sprite_size: &'static str,
}

#[derive(Debug, Clone)]
struct SpawnedSprite {
    var_name: String,
    sprite_index: u16,
    initial_x: i32,
    initial_y: i32,
    priority: u8,
    tile_base: u16,
    palette_slot: u8,
}

#[derive(Debug, Clone)]
struct AnimationState {
    var_name: String,
    state_name: String,
    sprite_index: u16,
    x_var: String,
    y_var: String,
    priority: u8,
    palette_slot: u8,
    frame_tiles: Vec<u16>,
    frame_time: u32,
    looping: bool,
}

#[derive(Debug, Clone)]
struct TilemapDraw {
    resource_name: String,
    bg_number: u8,
    scroll_x: i32,
    scroll_y: i32,
}

#[derive(Debug, Default)]
struct SnesContext {
    spawns: Vec<SpawnedSprite>,
    animations: Vec<AnimationState>,
    tilemaps: Vec<TilemapDraw>,
}

pub fn emit_snes(ast: &AstOutput, project_name: &str) -> EmitOutput {
    EmitOutput {
        main_c: build_main_c(ast, project_name),
        resources_res: build_resource_manifest(ast),
    }
}

fn build_main_c(ast: &AstOutput, project_name: &str) -> String {
    let mut out = String::new();
    let collision_checks = collect_collision_checks(ast);
    let physics_applications = collect_physics_applications(ast);
    let tilemap_assets = collect_tilemap_assets(ast);
    let parallax_layers = collect_parallax_layers(ast);
    let raster_lines = collect_raster_lines(ast);
    let scroll_tilemap_layers = collect_scroll_tilemap_layers(ast);
    let logic_vars = collect_logic_var_names(ast);
    let sfx_resources = collect_sfx_resources(ast);
    let bgm_tracks = collect_bgm_tracks(ast);
    let has_logic_overlap = ast.logic_scripts.iter().any(script_uses_overlap);
    let size_config = ast
        .sprite_assets
        .first()
        .and_then(|asset| sprite_size_config(asset.frame_width, asset.frame_height))
        .unwrap_or(SpriteSizeConfig {
            oam_size: "OBJ_SIZE16_L32",
            sprite_size: "OBJ_SMALL",
        });
    let tile_base_lookup = tile_base_lookup(ast);
    let context = build_context(ast, &tile_base_lookup);

    out.push_str("// Generated by RetroDev Studio - DO NOT EDIT\n");
    out.push_str(&format!("// Project: {}\n", project_name));
    out.push_str("// Target: SNES (PVSnesLib)\n\n");
    out.push_str("#include <snes.h>\n");
    for asset in &tilemap_assets {
        out.push_str(&format!("#include \"{}.inc\"\n", asset.resource_name));
    }
    for asset in &ast.sprite_assets {
        out.push_str(&format!("#include \"{}.inc\"\n", asset.resource_name));
    }
    out.push('\n');
    render_sound_id_macros(&mut out, ast);
    render_audio_externs(&mut out, &sfx_resources, &bgm_tracks);

    for animation in &context.animations {
        let frame_tiles = animation
            .frame_tiles
            .iter()
            .map(u16::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "static const u16 {}_tiles[] = {{{}}};\n",
            animation.state_name, frame_tiles
        ));
        out.push_str(&format!("static u16 {}_cursor = 0;\n", animation.state_name));
        out.push_str(&format!("static u16 {}_timer = 0;\n", animation.state_name));
    }
    if !context.animations.is_empty() {
        out.push('\n');
    }
    for spawn in &context.spawns {
        out.push_str(&format!(
            "static s16 {}_x = {};\n",
            spawn.var_name, spawn.initial_x
        ));
        out.push_str(&format!(
            "static s16 {}_y = {};\n",
            spawn.var_name, spawn.initial_y
        ));
    }
    if !context.spawns.is_empty() {
        out.push('\n');
    }
    for physics in &physics_applications {
        out.push_str(&format!("static s32 {}_vel_x = 0;\n", physics.var_name));
        out.push_str(&format!("static s32 {}_vel_y = 0;\n", physics.var_name));
    }
    if !physics_applications.is_empty() {
        out.push('\n');
    }
    for layer in &scroll_tilemap_layers {
        let layer_id = scroll_layer_id(layer);
        out.push_str(&format!("static s16 tm_scroll_x_{} = 0;\n", layer_id));
        out.push_str(&format!("static s16 tm_scroll_y_{} = 0;\n", layer_id));
    }
    if !scroll_tilemap_layers.is_empty() {
        out.push('\n');
    }
    for var_name in &logic_vars {
        out.push_str(&format!("static s32 logic_var_{} = 0;\n", var_name));
    }
    if !logic_vars.is_empty() {
        out.push('\n');
    }
    if !parallax_layers.is_empty() || !raster_lines.is_empty() {
        out.push_str("static u8 retro_hdma_table[449];\n");
        for (index, _) in parallax_layers.iter().enumerate() {
            out.push_str(&format!("static s16 retro_parallax_offset_{}_x = 0;\n", index));
            out.push_str(&format!("static s16 retro_parallax_offset_{}_y = 0;\n", index));
        }
        out.push('\n');
    }
    if !collision_checks.is_empty() || has_logic_overlap {
        out.push_str(render_aabb_helper());
        out.push('\n');
    }

    out.push_str("int main(void)\n{\n");
    out.push_str("    consoleInit();\n");
    out.push_str("    oamInit();\n");

    for tilemap in &context.tilemaps {
        let Some(asset) = tilemap_assets
            .iter()
            .find(|asset| asset.resource_name == tilemap.resource_name)
        else {
            continue;
        };
        out.push_str(&format!(
            "    bgInitTileSet({bg}, &{name}_til, &{name}_pal, 0, (&{name}_tilend - &{name}_til), (&{name}_palend - &{name}_pal), BG_16COLORS, 0x{tile_addr:04X});\n",
            bg = tilemap.bg_number,
            name = tilemap.resource_name,
            tile_addr = tilemap_tile_address(tilemap.bg_number)
        ));
        out.push_str(&format!(
            "    bgInitMapSet({bg}, (u8*)&{name}_map, (&{name}_mapend - &{name}_map), {size_mode}, 0x{map_addr:04X});\n",
            bg = tilemap.bg_number,
            name = tilemap.resource_name,
            size_mode = snes_map_size_mode(asset),
            map_addr = tilemap_map_address(tilemap.bg_number)
        ));
        if tilemap.scroll_x != 0 || tilemap.scroll_y != 0 {
            out.push_str(&format!(
                "    bgSetScroll({}, {}, {});\n",
                tilemap.bg_number, tilemap.scroll_x, tilemap.scroll_y
            ));
        }
    }

    let mut tile_base = 0u16;
    for asset in &ast.sprite_assets {
        let vram_address = tile_base.saturating_mul(16);
        out.push_str(&format!(
            "    oamInitGfxSet(&{name}_til, (&{name}_tilend - &{name}_til), &{name}_pal, (&{name}_palend - &{name}_pal), {palette}, 0x{address:04X}, {oam_size});\n",
            name = asset.resource_name,
            palette = asset.palette_slot,
            address = vram_address,
            oam_size = size_config.oam_size
        ));
        tile_base = tile_base.saturating_add(tile_count(asset));
    }

    for spawn in &context.spawns {
        let x_var = format!("{}_x", spawn.var_name);
        let y_var = format!("{}_y", spawn.var_name);
        out.push_str(&format!(
            "    oamSet({index}, {x}, {y}, {priority}, 0, 0, {tile}, {palette});\n",
            index = spawn.sprite_index,
            x = x_var,
            y = y_var,
            priority = spawn.priority,
            tile = initial_tile_for_spawn(&context, &spawn.var_name).unwrap_or(spawn.tile_base),
            palette = spawn.palette_slot
        ));
        out.push_str(&format!(
            "    oamSetEx({}, {}, OBJ_SHOW);\n",
            spawn.sprite_index, size_config.sprite_size
        ));
    }

    let mut pads_scanned = false;
    let mut retrofx_initialized = false;
    for node in &ast.nodes {
        match node {
            AstNode::SpriteSystemInit
            | AstNode::LoadTilemap { .. }
            | AstNode::LoadSpritesheet { .. }
            | AstNode::DrawTilemap { .. }
            | AstNode::SpawnSprite { .. }
            | AstNode::SetAnimation { .. } => {}
            AstNode::ScrollTilemap { layer, dx, dy } => {
                render_scroll_tilemap(&mut out, layer, *dx, *dy);
            }
            AstNode::MoveCamera { target, x, y } => {
                render_move_camera(&mut out, target, *x, *y);
            }
            AstNode::SetupParallax { layers } => {
                if !retrofx_initialized {
                    out.push_str("    setHDMATable(0, retro_hdma_table);\n");
                    retrofx_initialized = true;
                }
                out.push_str(&format!(
                    "    // RetroFX parallax configured for {} layer(s)\n",
                    layers.len()
                ));
            }
            AstNode::SetupRasterEffect { lines } => {
                if !retrofx_initialized {
                    out.push_str("    setHDMATable(0, retro_hdma_table);\n");
                    retrofx_initialized = true;
                }
                out.push_str(&format!(
                    "    // RetroFX raster configured for {} line(s)\n",
                    lines.len()
                ));
            }
            AstNode::InitAudio { sfx_resources } => {
                out.push_str("    spcBoot();\n");
                for (resource_name, _) in sfx_resources {
                    out.push_str(&format!(
                        "    spcSetSoundEntry(SFX_{sound_id}, 8, 0, (u8*)&{symbol});\n",
                        sound_id = resource_name.to_uppercase(),
                        symbol = snes_sfx_symbol(resource_name)
                    ));
                }
            }
            AstNode::PlayBgm { resource_name, .. } => {
                out.push_str(&format!(
                    "    spcLoad((u8*)&{});\n",
                    snes_bgm_symbol(resource_name)
                ));
            }
            AstNode::ReadInputDevice { device, state_var } => {
                if !pads_scanned {
                    out.push_str("        scanPads();\n");
                    pads_scanned = true;
                }
                out.push_str(&format!(
                    "        u16 {} = padsCurrent({});\n",
                    state_var,
                    snes_joypad_port(device)
                ));
            }
            AstNode::MapInputAction {
                result_name,
                entity_id,
                action_name,
                state_var,
                button,
            } => {
                render_input_binding(
                    &mut out,
                    result_name,
                    entity_id,
                    action_name,
                    state_var,
                    button,
                );
            }
            AstNode::CheckCollisionAabb {
                result_name,
                left,
                right,
            } => {
                render_collision_check(
                    &mut out,
                    &AabbCollisionCheck {
                        result_name: result_name.clone(),
                        left: left.clone(),
                        right: right.clone(),
                    },
                );
            }
            AstNode::ApplyPhysics {
                var_name,
                gravity,
                gravity_strength,
                max_velocity_x,
                max_velocity_y,
                friction,
                bounce,
            } => render_apply_physics(
                &mut out,
                &context,
                &PhysicsApplication {
                    var_name: var_name.clone(),
                    gravity: *gravity,
                    gravity_strength: *gravity_strength,
                    max_velocity_x: *max_velocity_x,
                    max_velocity_y: *max_velocity_y,
                    friction: *friction,
                    bounce: *bounce,
                },
            ),
            AstNode::DrawText { x, y, text, .. } => {
                let escaped = text.replace('"', "\\\"");
                out.push_str(&format!(
                    "    consoleDrawText({}, {}, \"{}\");\n",
                    x, y, escaped
                ));
            }
            AstNode::GameLoopBegin => {
                out.push_str("    setMode(BG_MODE1, 0);\n");
                if context.tilemaps.is_empty() {
                    out.push_str("    bgSetDisable(0);\n");
                    out.push_str("    bgSetDisable(1);\n");
                    out.push_str("    bgSetDisable(2);\n");
                } else {
                    for bg_number in 0..=2 {
                        if !context.tilemaps.iter().any(|tilemap| tilemap.bg_number == bg_number) {
                            out.push_str(&format!("    bgSetDisable({});\n", bg_number));
                        }
                    }
                }
                out.push_str("    setScreenOn();\n\n");
                out.push_str("    while (1)\n    {\n");
            }
            AstNode::SpriteUpdate => {
                render_logic_scripts(&mut out, &ast.logic_scripts, &context, 8);
                render_retrofx_frame(&mut out, &parallax_layers, &raster_lines, 8);
                for animation in &context.animations {
                    render_animation_update(&mut out, animation);
                }
                out.push_str("        oamUpdate();\n");
            }
            AstNode::VSync => {
                out.push_str("        WaitForVBlank();\n");
            }
            AstNode::GameLoopEnd => {
                out.push_str("    }\n");
            }
        }
    }

    out.push_str("\n    return 0;\n}\n");
    out
}

fn build_context(
    ast: &AstOutput,
    tile_base_lookup: &std::collections::HashMap<String, u16>,
) -> SnesContext {
    let mut context = SnesContext::default();
    let mut spawn_lookup: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let mut next_sprite_index = 0u16;
    let mut next_bg_number = 0u8;

    for node in &ast.nodes {
        match node {
            AstNode::DrawTilemap {
                resource_name,
                x,
                y,
                scroll_x,
                scroll_y,
            } => {
                context.tilemaps.push(TilemapDraw {
                    resource_name: resource_name.clone(),
                    bg_number: next_bg_number.min(2),
                    scroll_x: x.saturating_add(*scroll_x),
                    scroll_y: y.saturating_add(*scroll_y),
                });
                next_bg_number = next_bg_number.saturating_add(1);
            }
            AstNode::SpawnSprite {
                var_name,
                resource_name,
                x,
                y,
                priority_high,
            } => {
                let palette_slot = ast
                    .sprite_assets
                    .iter()
                    .find(|asset| asset.resource_name == *resource_name)
                    .map(|asset| asset.palette_slot)
                    .unwrap_or_default();
                let spawn = SpawnedSprite {
                    var_name: var_name.clone(),
                    sprite_index: next_sprite_index,
                    initial_x: *x,
                    initial_y: *y,
                    priority: if *priority_high { 3 } else { 0 },
                    tile_base: tile_base_lookup
                        .get(resource_name)
                        .copied()
                        .unwrap_or_default(),
                    palette_slot,
                };
                spawn_lookup.insert(var_name.clone(), context.spawns.len());
                context.spawns.push(spawn);
                next_sprite_index = next_sprite_index.saturating_add(1);
            }
            AstNode::SetAnimation {
                var_name,
                resource_name,
                frame_time,
                frames,
                looping,
                ..
            } => {
                let Some(spawn_index) = spawn_lookup.get(var_name).copied() else {
                    continue;
                };
                let Some(asset) = ast
                    .sprite_assets
                    .iter()
                    .find(|asset| asset.resource_name == *resource_name)
                else {
                    continue;
                };
                let spawn = &context.spawns[spawn_index];
                let frame_tiles = normalized_animation_frames(frames)
                    .into_iter()
                    .map(|frame| {
                        spawn
                            .tile_base
                            .saturating_add(frame.saturating_mul(tiles_per_frame(asset)))
                    })
                    .collect::<Vec<_>>();

                context.animations.push(AnimationState {
                    var_name: var_name.clone(),
                    state_name: format!("{}_anim", var_name),
                    sprite_index: spawn.sprite_index,
                    x_var: format!("{}_x", spawn.var_name),
                    y_var: format!("{}_y", spawn.var_name),
                    priority: spawn.priority,
                    palette_slot: spawn.palette_slot,
                    frame_tiles,
                    frame_time: *frame_time,
                    looping: *looping,
                });
            }
            _ => {}
        }
    }

    context
}

fn render_animation_update(out: &mut String, animation: &AnimationState) {
    if animation.frame_time == 0 || animation.frame_tiles.len() <= 1 {
        return;
    }

    let last_frame = animation.frame_tiles.len() - 1;
    out.push_str(&format!(
        "        if (++{name}_timer >= {delay}) {{\n",
        name = animation.state_name,
        delay = animation.frame_time
    ));
    out.push_str(&format!("            {}_timer = 0;\n", animation.state_name));
    out.push_str(&format!(
        "            if ({}_cursor < {}) {{\n",
        animation.state_name, last_frame
    ));
    out.push_str(&format!("                {}_cursor++;\n", animation.state_name));
    out.push_str(&format!(
        "                oamSet({index}, {x}, {y}, {priority}, 0, 0, {name}_tiles[{name}_cursor], {palette});\n",
        index = animation.sprite_index,
        x = animation.x_var,
        y = animation.y_var,
        priority = animation.priority,
        name = animation.state_name,
        palette = animation.palette_slot
    ));
    out.push_str("            }");
    if animation.looping {
        out.push_str(" else {\n");
        out.push_str(&format!("                {}_cursor = 0;\n", animation.state_name));
        out.push_str(&format!(
            "                oamSet({index}, {x}, {y}, {priority}, 0, 0, {name}_tiles[{name}_cursor], {palette});\n",
            index = animation.sprite_index,
            x = animation.x_var,
            y = animation.y_var,
            priority = animation.priority,
            name = animation.state_name,
            palette = animation.palette_slot
        ));
        out.push_str("            }\n");
    } else {
        out.push('\n');
    }
    out.push_str("        }\n");
}

fn render_scroll_tilemap(out: &mut String, layer: &str, dx: i32, dy: i32) {
    let layer_id = scroll_layer_id(layer);
    let bg = snes_bg_number(layer);
    out.push_str(&format!(
        "        tm_scroll_x_{layer_id} += {dx};\n",
        layer_id = layer_id,
        dx = dx
    ));
    out.push_str(&format!(
        "        tm_scroll_y_{layer_id} += {dy};\n",
        layer_id = layer_id,
        dy = dy
    ));
    out.push_str(&format!(
        "        bgSetScroll({bg}, tm_scroll_x_{layer_id}, tm_scroll_y_{layer_id});\n",
        bg = bg,
        layer_id = layer_id
    ));
}

fn render_move_camera(out: &mut String, target: &str, x: i32, y: i32) {
    let (x_expr, y_expr) = if target.starts_with("spr_") {
        (
            format!("{}_x + {}", target, x),
            format!("{}_y + {}", target, y),
        )
    } else {
        (x.to_string(), y.to_string())
    };

    out.push_str(&format!("        bgSetScroll(0, {}, {});\n", x_expr, y_expr));
}

fn render_aabb_helper() -> &'static str {
    "static u8 retro_aabb_intersects(s16 left_x, s16 left_y, u16 left_w, u16 left_h, s16 right_x, s16 right_y, u16 right_w, u16 right_h)\n\
{\n\
    return left_x < (right_x + (s16)right_w)\n\
        && (left_x + (s16)left_w) > right_x\n\
        && left_y < (right_y + (s16)right_h)\n\
        && (left_y + (s16)left_h) > right_y;\n\
}\n"
}

fn render_apply_physics(out: &mut String, context: &SnesContext, physics: &PhysicsApplication) {
    let Some(spawn) = context
        .spawns
        .iter()
        .find(|spawn| spawn.var_name == physics.var_name)
    else {
        return;
    };

    let x_var = format!("{}_x", physics.var_name);
    let y_var = format!("{}_y", physics.var_name);

    if physics.gravity {
        out.push_str(&format!(
            "        {var_name}_vel_y += {gravity_strength};\n",
            var_name = physics.var_name,
            gravity_strength = physics.gravity_strength
        ));
    }
    out.push_str(&format!(
        "        if ({var_name}_vel_x > {max_velocity_x}) {var_name}_vel_x = {max_velocity_x};\n",
        var_name = physics.var_name,
        max_velocity_x = physics.max_velocity_x
    ));
    out.push_str(&format!(
        "        if ({var_name}_vel_x < -{max_velocity_x}) {var_name}_vel_x = -{max_velocity_x};\n",
        var_name = physics.var_name,
        max_velocity_x = physics.max_velocity_x
    ));
    out.push_str(&format!(
        "        if ({var_name}_vel_y > {max_velocity_y}) {var_name}_vel_y = {max_velocity_y};\n",
        var_name = physics.var_name,
        max_velocity_y = physics.max_velocity_y
    ));
    out.push_str(&format!(
        "        if ({var_name}_vel_y < -{max_velocity_y}) {var_name}_vel_y = -{max_velocity_y};\n",
        var_name = physics.var_name,
        max_velocity_y = physics.max_velocity_y
    ));

    if physics.friction > 0 {
        out.push_str(&format!(
            "        if ({var_name}_vel_x > 0) {{ {var_name}_vel_x -= {friction}; if ({var_name}_vel_x < 0) {var_name}_vel_x = 0; }}\n",
            var_name = physics.var_name,
            friction = physics.friction
        ));
        out.push_str(&format!(
            "        if ({var_name}_vel_x < 0) {{ {var_name}_vel_x += {friction}; if ({var_name}_vel_x > 0) {var_name}_vel_x = 0; }}\n",
            var_name = physics.var_name,
            friction = physics.friction
        ));
    }

    out.push_str(&format!(
        "        {x_var} += ({var_name}_vel_x / 16);\n",
        x_var = x_var,
        var_name = physics.var_name
    ));
    out.push_str(&format!(
        "        {y_var} += ({var_name}_vel_y / 16);\n",
        y_var = y_var,
        var_name = physics.var_name
    ));

    if physics.bounce > 0 {
        out.push_str(&format!(
            "        if ({x_var} < 0) {{ {x_var} = 0; {var_name}_vel_x = -(({var_name}_vel_x * {bounce}) / 100); }}\n",
            x_var = x_var,
            var_name = physics.var_name,
            bounce = physics.bounce
        ));
        out.push_str(&format!(
            "        if ({y_var} < 0) {{ {y_var} = 0; {var_name}_vel_y = -(({var_name}_vel_y * {bounce}) / 100); }}\n",
            y_var = y_var,
            var_name = physics.var_name,
            bounce = physics.bounce
        ));
    }

    out.push_str(&format!(
        "        oamSet({index}, {x_var}, {y_var}, {priority}, 0, 0, {tile}, {palette});\n",
        index = spawn.sprite_index,
        x_var = x_var,
        y_var = y_var,
        priority = spawn.priority,
        tile = current_tile_expression(context, &physics.var_name),
        palette = spawn.palette_slot
    ));
}

fn render_logic_scripts(out: &mut String, scripts: &[LogicScript], context: &SnesContext, indent: usize) {
    for script in scripts {
        render_logic_ops(out, &script.ops, context, indent);
    }
}

fn render_logic_ops(out: &mut String, ops: &[LogicOp], context: &SnesContext, indent: usize) {
    let indent_str = " ".repeat(indent);
    let nested_indent = indent + 4;

    for op in ops {
        match op {
            LogicOp::MoveSprite { target_var, dx, dy } => {
                let Some(spawn) = context.spawns.iter().find(|spawn| spawn.var_name == *target_var) else {
                    continue;
                };

                out.push_str(&format!(
                    "{indent}{target}_x += {dx};\n",
                    indent = indent_str,
                    target = target_var,
                    dx = dx
                ));
                out.push_str(&format!(
                    "{indent}{target}_y += {dy};\n",
                    indent = indent_str,
                    target = target_var,
                    dy = dy
                ));
                out.push_str(&format!(
                    "{indent}oamSet({index}, {target}_x, {target}_y, {priority}, 0, 0, {tile}, {palette});\n",
                    indent = indent_str,
                    index = spawn.sprite_index,
                    target = target_var,
                    priority = spawn.priority,
                    tile = current_tile_expression(context, target_var),
                    palette = spawn.palette_slot
                ));
            }
            LogicOp::ConditionOverlap {
                left,
                right,
                if_true,
                if_false,
            } => {
                out.push_str(&format!(
                    "{indent}if (retro_aabb_intersects({left_x}, {left_y}, {left_w}, {left_h}, {right_x}, {right_y}, {right_w}, {right_h})) {{\n",
                    indent = indent_str,
                    left_x = logic_x_expr(left),
                    left_y = logic_y_expr(left),
                    left_w = left.width,
                    left_h = left.height,
                    right_x = logic_x_expr(right),
                    right_y = logic_y_expr(right),
                    right_w = right.width,
                    right_h = right.height
                ));
                render_logic_ops(out, if_true, context, nested_indent);
                if if_false.is_empty() {
                    out.push_str(&format!("{}}}\n", indent_str));
                } else {
                    out.push_str(&format!("{}}} else {{\n", indent_str));
                    render_logic_ops(out, if_false, context, nested_indent);
                    out.push_str(&format!("{}}}\n", indent_str));
                }
            }
            LogicOp::ConditionBool {
                condition,
                if_true,
                if_false,
            } => {
                let condition_expr = render_bool_expr(out, condition, indent);
                out.push_str(&format!(
                    "{indent}if ({condition}) {{\n",
                    indent = indent_str,
                    condition = condition_expr
                ));
                render_logic_ops(out, if_true, context, nested_indent);
                if if_false.is_empty() {
                    out.push_str(&format!("{}}}\n", indent_str));
                } else {
                    out.push_str(&format!("{}}} else {{\n", indent_str));
                    render_logic_ops(out, if_false, context, nested_indent);
                    out.push_str(&format!("{}}}\n", indent_str));
                }
            }
            LogicOp::PlaySound { sfx } => {
                out.push_str(&format!(
                    "{indent}spcPlaySound(SFX_{sfx});\n",
                    indent = indent_str,
                    sfx = sfx.to_uppercase()
                ));
            }
            LogicOp::SetVar { var_name, value } => {
                let value_expr = render_math_expr(value);
                out.push_str(&format!(
                    "{indent}logic_var_{var_name} = {value_expr};\n",
                    indent = indent_str,
                    var_name = var_name,
                    value_expr = value_expr
                ));
            }
        }
    }
}

fn render_bool_expr(out: &mut String, expr: &LogicBoolExpr, indent: usize) -> String {
    match expr {
        LogicBoolExpr::Literal(value) => {
            if *value { "1".to_string() } else { "0".to_string() }
        }
        LogicBoolExpr::Overlap { left, right } => format!(
            "retro_aabb_intersects({left_x}, {left_y}, {left_w}, {left_h}, {right_x}, {right_y}, {right_w}, {right_h})",
            left_x = logic_x_expr(left),
            left_y = logic_y_expr(left),
            left_w = left.width,
            left_h = left.height,
            right_x = logic_x_expr(right),
            right_y = logic_y_expr(right),
            right_w = right.width,
            right_h = right.height
        ),
        LogicBoolExpr::Not(value) => format!("!({})", render_bool_expr(out, value, indent)),
        LogicBoolExpr::And {
            result_name,
            left,
            right,
        } => {
            let left_expr = render_bool_expr(out, left, indent);
            let right_expr = render_bool_expr(out, right, indent);
            let indent_str = " ".repeat(indent);
            out.push_str(&format!(
                "{indent}u8 {result_name} = ({left} && {right});\n",
                indent = indent_str,
                result_name = result_name,
                left = left_expr,
                right = right_expr
            ));
            result_name.clone()
        }
        LogicBoolExpr::Compare { op, left, right } => {
            let left_expr = render_math_expr(left);
            let right_expr = render_math_expr(right);
            let op_str = match op {
                CompareOp::Eq => "==",
                CompareOp::Neq => "!=",
                CompareOp::Gt => ">",
                CompareOp::Gte => ">=",
                CompareOp::Lt => "<",
                CompareOp::Lte => "<=",
            };
            format!("({left_expr} {op_str} {right_expr})")
        }
    }
}

fn render_math_expr(expr: &LogicMathExpr) -> String {
    match expr {
        LogicMathExpr::Literal(val) => val.to_string(),
        LogicMathExpr::Var(name) => format!("logic_var_{}", name),
        LogicMathExpr::Add(left, right) => format!("({} + {})", render_math_expr(left), render_math_expr(right)),
        LogicMathExpr::Sub(left, right) => format!("({} - {})", render_math_expr(left), render_math_expr(right)),
        LogicMathExpr::Mul(left, right) => format!("({} * {})", render_math_expr(left), render_math_expr(right)),
        LogicMathExpr::Div(left, right) => format!("({} / {})", render_math_expr(left), render_math_expr(right)),
    }
}

fn render_retrofx_frame(
    out: &mut String,
    parallax_layers: &[ParallaxLayerConfig],
    raster_lines: &[RasterLineConfig],
    indent: usize,
) {
    if parallax_layers.is_empty() && raster_lines.is_empty() {
        return;
    }

    let indent_str = " ".repeat(indent);
    for (index, layer) in parallax_layers.iter().enumerate() {
        out.push_str(&format!(
            "{indent}retro_parallax_offset_{index}_x += {speed_x};\n",
            indent = indent_str,
            index = index,
            speed_x = layer.speed_x
        ));
        out.push_str(&format!(
            "{indent}retro_parallax_offset_{index}_y += {speed_y};\n",
            indent = indent_str,
            index = index,
            speed_y = layer.speed_y
        ));
    }

    out.push_str(&format!(
        "{indent}for (u16 retro_line = 0; retro_line < 224; retro_line++) {{\n",
        indent = indent_str
    ));
    out.push_str(&format!(
        "{indent}    retro_hdma_table[retro_line * 2] = 1;\n",
        indent = indent_str
    ));
    out.push_str(&format!(
        "{indent}    retro_hdma_table[(retro_line * 2) + 1] = 0;\n",
        indent = indent_str
    ));
    for (index, _) in parallax_layers.iter().enumerate() {
        let start = (index * 224) / parallax_layers.len();
        let end = ((index + 1) * 224) / parallax_layers.len();
        out.push_str(&format!(
            "{indent}    if (retro_line >= {start} && retro_line < {end}) retro_hdma_table[(retro_line * 2) + 1] = retro_parallax_offset_{index}_x;\n",
            indent = indent_str,
            start = start,
            end = end,
            index = index
        ));
    }
    out.push_str(&format!("{indent}}}\n", indent = indent_str));

    for line in raster_lines {
        out.push_str(&format!(
            "{indent}retro_hdma_table[({scanline} * 2) + 1] += {offset_x};\n",
            indent = indent_str,
            scanline = line.scanline,
            offset_x = line.offset_x
        ));
    }

    out.push_str(&format!(
        "{indent}retro_hdma_table[448] = 0;\n",
        indent = indent_str
    ));
    if !parallax_layers.is_empty() {
        out.push_str(&format!(
            "{indent}bgSetScroll(0, retro_parallax_offset_0_x, retro_parallax_offset_0_y);\n",
            indent = indent_str
        ));
    }
}

fn render_sound_id_macros(out: &mut String, ast: &AstOutput) {
    let sound_names = collect_sound_names(ast);
    if sound_names.is_empty() {
        return;
    }

    for (index, sound_name) in sound_names.iter().enumerate() {
        out.push_str(&format!(
            "#define SFX_{} {}\n",
            sound_name.to_uppercase(),
            index
        ));
    }
    out.push('\n');
}

fn render_audio_externs(
    out: &mut String,
    sfx_resources: &[(String, String)],
    bgm_tracks: &[(String, String)],
) {
    if sfx_resources.is_empty() && bgm_tracks.is_empty() {
        return;
    }

    for (resource_name, _) in sfx_resources {
        out.push_str(&format!(
            "extern char {};\n",
            snes_sfx_symbol(resource_name)
        ));
    }
    for (resource_name, _) in bgm_tracks {
        out.push_str(&format!(
            "extern char {};\n",
            snes_bgm_symbol(resource_name)
        ));
    }
    out.push('\n');
}

fn collect_sound_names(ast: &AstOutput) -> Vec<String> {
    let mut sound_names = std::collections::BTreeSet::new();
    for (resource_name, _) in collect_sfx_resources(ast) {
        sound_names.insert(resource_name);
    }
    for sound_name in collect_logic_sound_names(ast) {
        sound_names.insert(sound_name);
    }
    sound_names.into_iter().collect()
}

fn collect_logic_var_names(ast: &AstOutput) -> std::collections::BTreeSet<String> {
    let mut vars = std::collections::BTreeSet::new();
    for script in &ast.logic_scripts {
        for op in &script.ops {
            extract_vars_from_op(op, &mut vars);
        }
    }
    vars
}

fn extract_vars_from_op(op: &LogicOp, vars: &mut std::collections::BTreeSet<String>) {
    match op {
        LogicOp::SetVar { var_name, value } => {
            vars.insert(var_name.clone());
            extract_vars_from_math(value, vars);
        }
        LogicOp::ConditionOverlap { if_true, if_false, .. } => {
            for sub_op in if_true { extract_vars_from_op(sub_op, vars); }
            for sub_op in if_false { extract_vars_from_op(sub_op, vars); }
        }
        LogicOp::ConditionBool { condition, if_true, if_false } => {
            extract_vars_from_bool(condition, vars);
            for sub_op in if_true { extract_vars_from_op(sub_op, vars); }
            for sub_op in if_false { extract_vars_from_op(sub_op, vars); }
        }
        _ => {}
    }
}

fn extract_vars_from_bool(expr: &LogicBoolExpr, vars: &mut std::collections::BTreeSet<String>) {
    match expr {
        LogicBoolExpr::Compare { left, right, .. } => {
            extract_vars_from_math(left, vars);
            extract_vars_from_math(right, vars);
        }
        LogicBoolExpr::Not(inner) => extract_vars_from_bool(inner, vars),
        LogicBoolExpr::And { left, right, .. } => {
            extract_vars_from_bool(left, vars);
            extract_vars_from_bool(right, vars);
        }
        _ => {}
    }
}

fn extract_vars_from_math(expr: &LogicMathExpr, vars: &mut std::collections::BTreeSet<String>) {
    match expr {
        LogicMathExpr::Var(name) => { vars.insert(name.clone()); }
        LogicMathExpr::Add(left, right) | LogicMathExpr::Sub(left, right) | 
        LogicMathExpr::Mul(left, right) | LogicMathExpr::Div(left, right) => {
            extract_vars_from_math(left, vars);
            extract_vars_from_math(right, vars);
        }
        _ => {}
    }
}

fn snes_sfx_symbol(resource_name: &str) -> String {
    format!("{}_sfx", resource_name)
}

fn snes_bgm_symbol(resource_name: &str) -> String {
    format!("{}_bgm", resource_name)
}

fn current_tile_expression(context: &SnesContext, var_name: &str) -> String {
    context
        .animations
        .iter()
        .find(|animation| animation.var_name == var_name)
        .map(|animation| {
            format!(
                "{}_tiles[{}_cursor]",
                animation.state_name, animation.state_name
            )
        })
        .or_else(|| {
            context
                .spawns
                .iter()
                .find(|spawn| spawn.var_name == var_name)
                .map(|spawn| spawn.tile_base.to_string())
        })
        .unwrap_or_else(|| "0".to_string())
}

fn logic_x_expr(target: &LogicCollisionTarget) -> String {
    match &target.position {
        LogicPositionSource::SpriteVar { var_name } => format!("{}_x + {}", var_name, target.offset_x),
        LogicPositionSource::Static { x, .. } => (x + target.offset_x).to_string(),
    }
}

fn logic_y_expr(target: &LogicCollisionTarget) -> String {
    match &target.position {
        LogicPositionSource::SpriteVar { var_name } => format!("{}_y + {}", var_name, target.offset_y),
        LogicPositionSource::Static { y, .. } => (y + target.offset_y).to_string(),
    }
}

fn script_uses_overlap(script: &LogicScript) -> bool {
    script.ops.iter().any(op_uses_overlap)
}

fn op_uses_overlap(op: &LogicOp) -> bool {
    match op {
        LogicOp::ConditionOverlap { .. } => true,
        LogicOp::ConditionBool {
            condition,
            if_true,
            if_false,
        } => {
            bool_expr_uses_overlap(condition)
                || if_true.iter().any(op_uses_overlap)
                || if_false.iter().any(op_uses_overlap)
        }
        _ => false,
    }
}

fn bool_expr_uses_overlap(expr: &LogicBoolExpr) -> bool {
    match expr {
        LogicBoolExpr::Literal(_) => false,
        LogicBoolExpr::Overlap { .. } => true,
        LogicBoolExpr::Compare { .. } => false,
        LogicBoolExpr::Not(value) => bool_expr_uses_overlap(value),
        LogicBoolExpr::And { left, right, .. } => {
            bool_expr_uses_overlap(left) || bool_expr_uses_overlap(right)
        }
    }
}

fn render_collision_check(out: &mut String, check: &AabbCollisionCheck) {
    out.push_str(&format!(
        "        u8 {result_name} = retro_aabb_intersects({left_x}, {left_y}, {left_width}, {left_height}, {right_x}, {right_y}, {right_width}, {right_height});\n",
        result_name = check.result_name,
        left_x = check.left.x,
        left_y = check.left.y,
        left_width = check.left.width,
        left_height = check.left.height,
        right_x = check.right.x,
        right_y = check.right.y,
        right_width = check.right.width,
        right_height = check.right.height
    ));
    out.push_str(&format!(
        "        if ({}) {{\n            // Collision: {} <-> {}\n        }}\n",
        check.result_name, check.left.entity_id, check.right.entity_id
    ));
}

fn render_input_binding(
    out: &mut String,
    result_name: &str,
    entity_id: &str,
    action_name: &str,
    state_var: &str,
    button: &str,
) {
    let Some(button_mask) = snes_button_mask(button) else {
        out.push_str(&format!(
            "        // Unsupported input mapping on SNES: {}.{} -> {}\n",
            entity_id, action_name, button
        ));
        return;
    };

    out.push_str(&format!(
        "        u16 {result_name} = {state_var} & {button_mask};\n",
        result_name = result_name,
        state_var = state_var,
        button_mask = button_mask
    ));
    out.push_str(&format!(
        "        if ({}) {{\n            // Input: {}.{}\n        }}\n",
        result_name, entity_id, action_name
    ));
}

fn snes_joypad_port(device: &str) -> u8 {
    match device {
        "joypad_2" => 1,
        _ => 0,
    }
}

fn snes_button_mask(button: &str) -> Option<&'static str> {
    match button {
        "DPAD_UP" => Some("KEY_UP"),
        "DPAD_DOWN" => Some("KEY_DOWN"),
        "DPAD_LEFT" => Some("KEY_LEFT"),
        "DPAD_RIGHT" => Some("KEY_RIGHT"),
        "BUTTON_A" => Some("KEY_A"),
        "BUTTON_B" => Some("KEY_B"),
        "BUTTON_X" => Some("KEY_X"),
        "BUTTON_Y" => Some("KEY_Y"),
        "START" => Some("KEY_START"),
        "SELECT" => Some("KEY_SELECT"),
        _ => None,
    }
}

fn initial_tile_for_spawn(context: &SnesContext, var_name: &str) -> Option<u16> {
    context
        .animations
        .iter()
        .find(|animation| animation.state_name == format!("{}_anim", var_name))
        .and_then(|animation| animation.frame_tiles.first().copied())
}

fn tile_base_lookup(ast: &AstOutput) -> std::collections::HashMap<String, u16> {
    let mut lookup = std::collections::HashMap::new();
    let mut accumulated_tiles = 0u16;

    for asset in &ast.sprite_assets {
        lookup.insert(asset.resource_name.clone(), accumulated_tiles);
        accumulated_tiles = accumulated_tiles.saturating_add(tile_count(asset));
    }

    lookup
}

fn build_resource_manifest(ast: &AstOutput) -> String {
    let mut out = String::new();
    let tilemap_assets = collect_tilemap_assets(ast);
    let sfx_resources = collect_sfx_resources(ast);
    let bgm_tracks = collect_bgm_tracks(ast);
    out.push_str("// Generated by RetroDev Studio - DO NOT EDIT\n");
    out.push_str("// Workspace SNES asset manifest\n\n");

    if ast.sprite_assets.is_empty()
        && tilemap_assets.is_empty()
        && sfx_resources.is_empty()
        && bgm_tracks.is_empty()
    {
        out.push_str("# no visual assets staged for this target\n");
        return out;
    }

    for asset in &tilemap_assets {
        out.push_str(&format!(
            "BMP {} <- {} ({}x{} tiles)\n",
            asset.resource_name, asset.asset_path, asset.map_width, asset.map_height
        ));
    }

    for asset in &ast.sprite_assets {
        out.push_str(&format!(
            "BMP {} <- {} ({}x{}, pal {})\n",
            asset.resource_name,
            asset.asset_path,
            asset.frame_width,
            asset.frame_height,
            asset.palette_slot
        ));
    }
    for (resource_name, asset_path) in sfx_resources {
        out.push_str(&format!("SFX {} <- {}\n", resource_name, asset_path));
    }
    for (resource_name, asset_path) in bgm_tracks {
        out.push_str(&format!("BGM {} <- {}\n", resource_name, asset_path));
    }

    out
}

fn sprite_size_config(frame_width: u32, frame_height: u32) -> Option<SpriteSizeConfig> {
    if frame_width != frame_height {
        return None;
    }

    match frame_width {
        8 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE8_L16",
            sprite_size: "OBJ_SMALL",
        }),
        16 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE16_L32",
            sprite_size: "OBJ_SMALL",
        }),
        32 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE32_L64",
            sprite_size: "OBJ_SMALL",
        }),
        64 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE32_L64",
            sprite_size: "OBJ_LARGE",
        }),
        _ => None,
    }
}

fn normalized_animation_frames(frames: &[u32]) -> Vec<u16> {
    if frames.is_empty() {
        vec![0]
    } else {
        frames
            .iter()
            .map(|frame| (*frame).min(u16::MAX as u32) as u16)
            .collect()
    }
}

fn tiles_per_frame(asset: &SpriteAsset) -> u16 {
    let width_tiles = (asset.frame_width / 8).max(1);
    let height_tiles = (asset.frame_height / 8).max(1);
    (width_tiles * height_tiles).min(u16::MAX as u32) as u16
}

fn tile_count(asset: &SpriteAsset) -> u16 {
    let frame_count = asset.animation_count.max(1);
    (u32::from(tiles_per_frame(asset)) * frame_count).min(u16::MAX as u32) as u16
}

fn collect_scroll_tilemap_layers(ast: &AstOutput) -> Vec<String> {
    let mut layers = Vec::new();
    for node in &ast.nodes {
        if let AstNode::ScrollTilemap { layer, .. } = node {
            if !layers.iter().any(|existing| existing == layer) {
                layers.push(layer.clone());
            }
        }
    }
    layers
}

fn snes_bg_number(layer: &str) -> u8 {
    match layer {
        "BG_B" | "BG2" => 1,
        "WINDOW" | "BG3" => 2,
        _ => 0,
    }
}

fn scroll_layer_id(layer: &str) -> String {
    layer
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn snes_map_size_mode(asset: &TilemapAsset) -> &'static str {
    match (asset.map_width > 32, asset.map_height > 32) {
        (false, false) => "SC_32x32",
        (true, false) => "SC_64x32",
        (false, true) => "SC_32x64",
        (true, true) => "SC_64x64",
    }
}

fn tilemap_tile_address(bg_number: u8) -> u16 {
    0x2000 + (u16::from(bg_number) * 0x1000)
}

fn tilemap_map_address(bg_number: u8) -> u16 {
    u16::from(bg_number) * 0x1000
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::ast_generator::{
        LogicCollisionTarget, LogicOp, LogicPositionSource, LogicScript, SpriteAnimation,
    };

    fn sprite_asset() -> SpriteAsset {
        let animation = SpriteAnimation {
            name: "walk".to_string(),
            frames: vec![0, 1, 2],
            frame_time: 6,
            looping: true,
        };
        SpriteAsset {
            resource_name: "hero".to_string(),
            asset_path: "assets/sprites/hero.png".to_string(),
            frame_width: 16,
            frame_height: 16,
            palette_slot: 0,
            animation_count: 3,
            animations: vec![animation.clone()],
            default_animation: Some(animation),
        }
    }

    fn logic_script() -> LogicScript {
        LogicScript {
            ops: vec![
                LogicOp::MoveSprite {
                    target_var: "spr_hero".to_string(),
                    dx: 2,
                    dy: -1,
                },
                LogicOp::ConditionOverlap {
                    left: LogicCollisionTarget {
                        entity_id: "hero".to_string(),
                        position: LogicPositionSource::SpriteVar {
                            var_name: "spr_hero".to_string(),
                        },
                        offset_x: 0,
                        offset_y: 0,
                        width: 16,
                        height: 16,
                    },
                    right: LogicCollisionTarget {
                        entity_id: "enemy".to_string(),
                        position: LogicPositionSource::SpriteVar {
                            var_name: "spr_enemy".to_string(),
                        },
                        offset_x: 1,
                        offset_y: 2,
                        width: 16,
                        height: 16,
                    },
                    if_true: vec![LogicOp::PlaySound {
                        sfx: "jump".to_string(),
                    }],
                    if_false: Vec::new(),
                },
            ],
        }
    }

    #[test]
    fn snes_emitter_generates_frame_timer_for_default_animation() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::SpriteSystemInit,
                AstNode::LoadSpritesheet {
                    resource_name: "hero".to_string(),
                    asset_path: "assets/sprites/hero.png".to_string(),
                    frame_width: 16,
                    frame_height: 16,
                    palette_slot: 0,
                },
                AstNode::SpawnSprite {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    x: 32,
                    y: 48,
                    priority_high: true,
                },
                AstNode::SetAnimation {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    anim_index: 0,
                    frame_time: 6,
                    frames: vec![0, 1, 2],
                    looping: true,
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: vec![sprite_asset()],
            logic_scripts: Vec::new(),
        };

        let output = emit_snes(&ast, "Timing Demo");

        assert!(output
            .main_c
            .contains("static const u16 spr_hero_anim_tiles[] = {0, 4, 8};"));
        assert!(output.main_c.contains("static s16 spr_hero_x = 32;"));
        assert!(output.main_c.contains("static s16 spr_hero_y = 48;"));
        assert!(output.main_c.contains("if (++spr_hero_anim_timer >= 6)"));
        assert!(output
            .main_c
            .contains("oamSet(0, spr_hero_x, spr_hero_y, 3, 0, 0, spr_hero_anim_tiles[spr_hero_anim_cursor], 0);"));
    }

    #[test]
    fn snes_emitter_initializes_tilemap_backgrounds() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::LoadTilemap {
                    resource_name: "background_tilemap".to_string(),
                    asset_path: "assets/tilesets/level.ppm".to_string(),
                    map_width: 64,
                    map_height: 32,
                },
                AstNode::DrawTilemap {
                    resource_name: "background_tilemap".to_string(),
                    x: 16,
                    y: 24,
                    scroll_x: 8,
                    scroll_y: 4,
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
            logic_scripts: Vec::new(),
        };

        let output = emit_snes(&ast, "Tilemap Demo");

        assert!(output.main_c.contains("#include \"background_tilemap.inc\""));
        assert!(output.main_c.contains(
            "bgInitTileSet(0, &background_tilemap_til, &background_tilemap_pal, 0, (&background_tilemap_tilend - &background_tilemap_til), (&background_tilemap_palend - &background_tilemap_pal), BG_16COLORS, 0x2000);"
        ));
        assert!(output.main_c.contains(
            "bgInitMapSet(0, (u8*)&background_tilemap_map, (&background_tilemap_mapend - &background_tilemap_map), SC_64x32, 0x0000);"
        ));
        assert!(output.main_c.contains("bgSetScroll(0, 24, 28);"));
    }

    #[test]
    fn snes_emitter_emits_manual_aabb_collision_checks() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::CheckCollisionAabb {
                    result_name: "collision_player_badnik".to_string(),
                    left: crate::compiler::ast_generator::CollisionBox {
                        entity_id: "player".to_string(),
                        x: 18,
                        y: 28,
                        width: 16,
                        height: 24,
                    },
                    right: crate::compiler::ast_generator::CollisionBox {
                        entity_id: "badnik".to_string(),
                        x: 40,
                        y: 28,
                        width: 24,
                        height: 24,
                    },
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
            logic_scripts: Vec::new(),
        };

        let output = emit_snes(&ast, "Collision Demo");

        assert!(output.main_c.contains("static u8 retro_aabb_intersects("));
        assert!(output.main_c.contains(
            "u8 collision_player_badnik = retro_aabb_intersects(18, 28, 16, 24, 40, 28, 24, 24);"
        ));
        assert!(output
            .main_c
            .contains("// Collision: player <-> badnik"));
    }

    #[test]
    fn snes_emitter_reads_input_mappings() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::ReadInputDevice {
                    device: "joypad_1".to_string(),
                    state_var: "joypad_1_state".to_string(),
                },
                AstNode::MapInputAction {
                    result_name: "input_player_move_left".to_string(),
                    entity_id: "player".to_string(),
                    action_name: "move_left".to_string(),
                    state_var: "joypad_1_state".to_string(),
                    button: "DPAD_LEFT".to_string(),
                },
                AstNode::MapInputAction {
                    result_name: "input_player_jump".to_string(),
                    entity_id: "player".to_string(),
                    action_name: "jump".to_string(),
                    state_var: "joypad_1_state".to_string(),
                    button: "BUTTON_A".to_string(),
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
            logic_scripts: Vec::new(),
        };

        let output = emit_snes(&ast, "Input Demo");

        assert!(output.main_c.contains("scanPads();"));
        assert!(output
            .main_c
            .contains("u16 joypad_1_state = padsCurrent(0);"));
        assert!(output
            .main_c
            .contains("u16 input_player_move_left = joypad_1_state & KEY_LEFT;"));
        assert!(output
            .main_c
            .contains("u16 input_player_jump = joypad_1_state & KEY_A;"));
        assert!(output.main_c.contains("// Input: player.move_left"));
        assert!(output.main_c.contains("// Input: player.jump"));
    }

    #[test]
    fn snes_emitter_emits_audio_boot_and_manifest_entries() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::InitAudio {
                    sfx_resources: vec![("jump".to_string(), "assets/audio/jump.brr".to_string())],
                },
                AstNode::PlayBgm {
                    resource_name: "stage_theme".to_string(),
                    asset_path: "assets/audio/stage_theme.spc".to_string(),
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
            logic_scripts: vec![logic_script()],
        };

        let output = emit_snes(&ast, "Audio Demo");

        assert!(output.main_c.contains("#define SFX_JUMP 0"));
        assert!(output.main_c.contains("extern char jump_sfx;"));
        assert!(output.main_c.contains("extern char stage_theme_bgm;"));
        assert!(output.main_c.contains("spcBoot();"));
        assert!(output
            .main_c
            .contains("spcSetSoundEntry(SFX_JUMP, 8, 0, (u8*)&jump_sfx);"));
        assert!(output
            .main_c
            .contains("spcLoad((u8*)&stage_theme_bgm);"));
        assert!(output
            .resources_res
            .contains("SFX jump <- assets/audio/jump.brr"));
        assert!(output
            .resources_res
            .contains("BGM stage_theme <- assets/audio/stage_theme.spc"));
    }

    #[test]
    fn snes_emitter_emits_retrofx_hdma_setup_and_frame_updates() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::SetupParallax {
                    layers: vec![ParallaxLayerConfig {
                        layer_name: "BG1".to_string(),
                        speed_x: 2,
                        speed_y: 1,
                    }],
                },
                AstNode::SetupRasterEffect {
                    lines: vec![RasterLineConfig {
                        scanline: 128,
                        offset_x: 6,
                    }],
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
            logic_scripts: Vec::new(),
        };

        let output = emit_snes(&ast, "RetroFX Demo");

        assert!(output.main_c.contains("static u8 retro_hdma_table[449];"));
        assert!(output.main_c.contains("setHDMATable(0, retro_hdma_table);"));
        assert!(output.main_c.contains("retro_parallax_offset_0_x += 2;"));
        assert!(output.main_c.contains("retro_parallax_offset_0_y += 1;"));
        assert!(output
            .main_c
            .contains("retro_hdma_table[(128 * 2) + 1] += 6;"));
        assert!(output
            .main_c
            .contains("bgSetScroll(0, retro_parallax_offset_0_x, retro_parallax_offset_0_y);"));
    }

    #[test]
    fn snes_emitter_emits_apply_physics_with_velocity_state() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::SpawnSprite {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    x: 32,
                    y: 48,
                    priority_high: true,
                },
                AstNode::SetAnimation {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    anim_index: 0,
                    frame_time: 6,
                    frames: vec![0, 1, 2],
                    looping: true,
                },
                AstNode::GameLoopBegin,
                AstNode::ApplyPhysics {
                    var_name: "spr_hero".to_string(),
                    gravity: true,
                    gravity_strength: 6,
                    max_velocity_x: 48,
                    max_velocity_y: 96,
                    friction: 2,
                    bounce: 35,
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: vec![sprite_asset()],
            logic_scripts: Vec::new(),
        };

        let output = emit_snes(&ast, "Physics Demo");

        assert!(output.main_c.contains("static s32 spr_hero_vel_x = 0;"));
        assert!(output.main_c.contains("static s32 spr_hero_vel_y = 0;"));
        assert!(output.main_c.contains("spr_hero_vel_y += 6;"));
        assert!(output.main_c.contains("if (spr_hero_vel_x > 48) spr_hero_vel_x = 48;"));
        assert!(output.main_c.contains("spr_hero_x += (spr_hero_vel_x / 16);"));
        assert!(output.main_c.contains("spr_hero_y += (spr_hero_vel_y / 16);"));
        assert!(output.main_c.contains(
            "oamSet(0, spr_hero_x, spr_hero_y, 3, 0, 0, spr_hero_anim_tiles[spr_hero_anim_cursor], 0);"
        ));
    }

    #[test]
    fn snes_emitter_emits_runtime_tilemap_scroll_and_camera_commands() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::ScrollTilemap {
                    layer: "BG_B".to_string(),
                    dx: 3,
                    dy: -2,
                },
                AstNode::MoveCamera {
                    target: "spr_hero".to_string(),
                    x: 12,
                    y: -4,
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
            logic_scripts: Vec::new(),
        };

        let output = emit_snes(&ast, "Scroll Demo");

        assert!(output.main_c.contains("static s16 tm_scroll_x_bg_b = 0;"));
        assert!(output.main_c.contains("static s16 tm_scroll_y_bg_b = 0;"));
        assert!(output.main_c.contains("tm_scroll_x_bg_b += 3;"));
        assert!(output.main_c.contains("tm_scroll_y_bg_b += -2;"));
        assert!(output
            .main_c
            .contains("bgSetScroll(1, tm_scroll_x_bg_b, tm_scroll_y_bg_b);"));
        assert!(output
            .main_c
            .contains("bgSetScroll(0, spr_hero_x + 12, spr_hero_y + -4);"));
    }

    #[test]
    fn snes_emitter_emits_nodegraph_logic_inside_game_loop() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::SpawnSprite {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    x: 32,
                    y: 48,
                    priority_high: true,
                },
                AstNode::SpawnSprite {
                    var_name: "spr_enemy".to_string(),
                    resource_name: "hero".to_string(),
                    x: 96,
                    y: 48,
                    priority_high: false,
                },
                AstNode::SetAnimation {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    anim_index: 0,
                    frame_time: 6,
                    frames: vec![0, 1, 2],
                    looping: true,
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: vec![sprite_asset()],
            logic_scripts: vec![logic_script()],
        };

        let output = emit_snes(&ast, "Logic Demo");

        assert!(output.main_c.contains("static u8 retro_aabb_intersects("));
        assert!(output.main_c.contains("spr_hero_x += 2;"));
        assert!(output.main_c.contains("spr_hero_y += -1;"));
        assert!(output.main_c.contains(
            "oamSet(0, spr_hero_x, spr_hero_y, 3, 0, 0, spr_hero_anim_tiles[spr_hero_anim_cursor], 0);"
        ));
        assert!(output.main_c.contains(
            "if (retro_aabb_intersects(spr_hero_x + 0, spr_hero_y + 0, 16, 16, spr_enemy_x + 1, spr_enemy_y + 2, 16, 16)) {"
        ));
        assert!(output.main_c.contains("spcPlaySound(SFX_JUMP);"));
    }

    #[test]
    fn snes_emitter_emits_logic_var_math_and_compare_branching() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
            logic_scripts: vec![LogicScript {
                ops: vec![
                    LogicOp::SetVar {
                        var_name: "score".to_string(),
                        value: LogicMathExpr::Div(
                            Box::new(LogicMathExpr::Mul(
                                Box::new(LogicMathExpr::Add(
                                    Box::new(LogicMathExpr::Var("score".to_string())),
                                    Box::new(LogicMathExpr::Literal(2)),
                                )),
                                Box::new(LogicMathExpr::Sub(
                                    Box::new(LogicMathExpr::Literal(6)),
                                    Box::new(LogicMathExpr::Literal(1)),
                                )),
                            )),
                            Box::new(LogicMathExpr::Literal(5)),
                        ),
                    },
                    LogicOp::ConditionBool {
                        condition: LogicBoolExpr::Compare {
                            op: CompareOp::Gte,
                            left: Box::new(LogicMathExpr::Var("score".to_string())),
                            right: Box::new(LogicMathExpr::Literal(10)),
                        },
                        if_true: vec![LogicOp::PlaySound {
                            sfx: "win".to_string(),
                        }],
                        if_false: vec![LogicOp::PlaySound {
                            sfx: "lose".to_string(),
                        }],
                    },
                ],
            }],
        };

        let output = emit_snes(&ast, "Logic Vars Demo");

        assert!(output.main_c.contains("static s32 logic_var_score = 0;"));
        assert!(output.main_c.contains("logic_var_score = (((logic_var_score + 2) * (6 - 1)) / 5);"));
        assert!(output.main_c.contains("if ((logic_var_score >= 10)) {"));
        assert!(output.main_c.contains("spcPlaySound(SFX_WIN);"));
        assert!(output.main_c.contains("} else {"));
        assert!(output.main_c.contains("spcPlaySound(SFX_LOSE);"));
    }
}
