use crate::compiler::ast_generator::{
    collect_collision_checks, collect_tilemap_assets, AabbCollisionCheck, AstNode, AstOutput,
    SpriteAsset, TilemapAsset,
};

#[derive(Debug)]
pub struct EmitOutput {
    pub main_c: String,
    pub resources_res: String,
}

#[derive(Debug, Clone, Copy)]
struct SpriteSizeConfig {
    oam_size: &'static str,
    sprite_size: &'static str,
}

#[derive(Debug, Clone)]
struct SpawnedSprite {
    var_name: String,
    sprite_index: u16,
    x: i32,
    y: i32,
    priority: u8,
    tile_base: u16,
    palette_slot: u8,
}

#[derive(Debug, Clone)]
struct AnimationState {
    state_name: String,
    sprite_index: u16,
    x: i32,
    y: i32,
    priority: u8,
    palette_slot: u8,
    frame_tiles: Vec<u16>,
    frame_time: u32,
    looping: bool,
}

#[derive(Debug, Clone)]
struct TilemapDraw {
    resource_name: String,
    bg_number: u8,
    scroll_x: i32,
    scroll_y: i32,
}

#[derive(Debug, Default)]
struct SnesContext {
    spawns: Vec<SpawnedSprite>,
    animations: Vec<AnimationState>,
    tilemaps: Vec<TilemapDraw>,
}

pub fn emit_snes(ast: &AstOutput, project_name: &str) -> EmitOutput {
    EmitOutput {
        main_c: build_main_c(ast, project_name),
        resources_res: build_resource_manifest(ast),
    }
}

fn build_main_c(ast: &AstOutput, project_name: &str) -> String {
    let mut out = String::new();
    let collision_checks = collect_collision_checks(ast);
    let tilemap_assets = collect_tilemap_assets(ast);
    let size_config = ast
        .sprite_assets
        .first()
        .and_then(|asset| sprite_size_config(asset.frame_width, asset.frame_height))
        .unwrap_or(SpriteSizeConfig {
            oam_size: "OBJ_SIZE16_L32",
            sprite_size: "OBJ_SMALL",
        });
    let tile_base_lookup = tile_base_lookup(ast);
    let context = build_context(ast, &tile_base_lookup);

    out.push_str("// Generated by RetroDev Studio - DO NOT EDIT\n");
    out.push_str(&format!("// Project: {}\n", project_name));
    out.push_str("// Target: SNES (PVSnesLib)\n\n");
    out.push_str("#include <snes.h>\n");
    for asset in &tilemap_assets {
        out.push_str(&format!("#include \"{}.inc\"\n", asset.resource_name));
    }
    for asset in &ast.sprite_assets {
        out.push_str(&format!("#include \"{}.inc\"\n", asset.resource_name));
    }
    out.push('\n');

    for animation in &context.animations {
        let frame_tiles = animation
            .frame_tiles
            .iter()
            .map(u16::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "static const u16 {}_tiles[] = {{{}}};\n",
            animation.state_name, frame_tiles
        ));
        out.push_str(&format!("static u16 {}_cursor = 0;\n", animation.state_name));
        out.push_str(&format!("static u16 {}_timer = 0;\n", animation.state_name));
    }
    if !context.animations.is_empty() {
        out.push('\n');
    }
    if !collision_checks.is_empty() {
        out.push_str(render_aabb_helper());
        out.push('\n');
    }

    out.push_str("int main(void)\n{\n");
    out.push_str("    consoleInit();\n");
    out.push_str("    oamInit();\n");

    for tilemap in &context.tilemaps {
        let Some(asset) = tilemap_assets
            .iter()
            .find(|asset| asset.resource_name == tilemap.resource_name)
        else {
            continue;
        };
        out.push_str(&format!(
            "    bgInitTileSet({bg}, &{name}_til, &{name}_pal, 0, (&{name}_tilend - &{name}_til), (&{name}_palend - &{name}_pal), BG_16COLORS, 0x{tile_addr:04X});\n",
            bg = tilemap.bg_number,
            name = tilemap.resource_name,
            tile_addr = tilemap_tile_address(tilemap.bg_number)
        ));
        out.push_str(&format!(
            "    bgInitMapSet({bg}, (u8*)&{name}_map, (&{name}_mapend - &{name}_map), {size_mode}, 0x{map_addr:04X});\n",
            bg = tilemap.bg_number,
            name = tilemap.resource_name,
            size_mode = snes_map_size_mode(asset),
            map_addr = tilemap_map_address(tilemap.bg_number)
        ));
        if tilemap.scroll_x != 0 || tilemap.scroll_y != 0 {
            out.push_str(&format!(
                "    bgSetScroll({}, {}, {});\n",
                tilemap.bg_number, tilemap.scroll_x, tilemap.scroll_y
            ));
        }
    }

    let mut tile_base = 0u16;
    for asset in &ast.sprite_assets {
        let vram_address = tile_base.saturating_mul(16);
        out.push_str(&format!(
            "    oamInitGfxSet(&{name}_til, (&{name}_tilend - &{name}_til), &{name}_pal, (&{name}_palend - &{name}_pal), {palette}, 0x{address:04X}, {oam_size});\n",
            name = asset.resource_name,
            palette = asset.palette_slot,
            address = vram_address,
            oam_size = size_config.oam_size
        ));
        tile_base = tile_base.saturating_add(tile_count(asset));
    }

    for spawn in &context.spawns {
        out.push_str(&format!(
            "    oamSet({index}, {x}, {y}, {priority}, 0, 0, {tile}, {palette});\n",
            index = spawn.sprite_index,
            x = spawn.x.max(0),
            y = spawn.y.max(0),
            priority = spawn.priority,
            tile = initial_tile_for_spawn(&context, &spawn.var_name).unwrap_or(spawn.tile_base),
            palette = spawn.palette_slot
        ));
        out.push_str(&format!(
            "    oamSetEx({}, {}, OBJ_SHOW);\n",
            spawn.sprite_index, size_config.sprite_size
        ));
    }

    let mut pads_scanned = false;
    for node in &ast.nodes {
        match node {
            AstNode::SpriteSystemInit
            | AstNode::LoadTilemap { .. }
            | AstNode::LoadSpritesheet { .. }
            | AstNode::DrawTilemap { .. }
            | AstNode::SpawnSprite { .. }
            | AstNode::SetAnimation { .. } => {}
            AstNode::ReadInputDevice { device, state_var } => {
                if !pads_scanned {
                    out.push_str("        scanPads();\n");
                    pads_scanned = true;
                }
                out.push_str(&format!(
                    "        u16 {} = padsCurrent({});\n",
                    state_var,
                    snes_joypad_port(device)
                ));
            }
            AstNode::MapInputAction {
                result_name,
                entity_id,
                action_name,
                state_var,
                button,
            } => {
                render_input_binding(
                    &mut out,
                    result_name,
                    entity_id,
                    action_name,
                    state_var,
                    button,
                );
            }
            AstNode::CheckCollisionAabb {
                result_name,
                left,
                right,
            } => {
                render_collision_check(
                    &mut out,
                    &AabbCollisionCheck {
                        result_name: result_name.clone(),
                        left: left.clone(),
                        right: right.clone(),
                    },
                );
            }
            AstNode::DrawText { x, y, text, .. } => {
                let escaped = text.replace('"', "\\\"");
                out.push_str(&format!(
                    "    consoleDrawText({}, {}, \"{}\");\n",
                    x, y, escaped
                ));
            }
            AstNode::GameLoopBegin => {
                out.push_str("    setMode(BG_MODE1, 0);\n");
                if context.tilemaps.is_empty() {
                    out.push_str("    bgSetDisable(0);\n");
                    out.push_str("    bgSetDisable(1);\n");
                    out.push_str("    bgSetDisable(2);\n");
                } else {
                    for bg_number in 0..=2 {
                        if !context.tilemaps.iter().any(|tilemap| tilemap.bg_number == bg_number) {
                            out.push_str(&format!("    bgSetDisable({});\n", bg_number));
                        }
                    }
                }
                out.push_str("    setScreenOn();\n\n");
                out.push_str("    while (1)\n    {\n");
            }
            AstNode::SpriteUpdate => {
                for animation in &context.animations {
                    render_animation_update(&mut out, animation);
                }
                out.push_str("        oamUpdate();\n");
            }
            AstNode::VSync => {
                out.push_str("        WaitForVBlank();\n");
            }
            AstNode::GameLoopEnd => {
                out.push_str("    }\n");
            }
        }
    }

    out.push_str("\n    return 0;\n}\n");
    out
}

fn build_context(
    ast: &AstOutput,
    tile_base_lookup: &std::collections::HashMap<String, u16>,
) -> SnesContext {
    let mut context = SnesContext::default();
    let mut spawn_lookup: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    let mut next_sprite_index = 0u16;
    let mut next_bg_number = 0u8;

    for node in &ast.nodes {
        match node {
            AstNode::DrawTilemap {
                resource_name,
                x,
                y,
                scroll_x,
                scroll_y,
            } => {
                context.tilemaps.push(TilemapDraw {
                    resource_name: resource_name.clone(),
                    bg_number: next_bg_number.min(2),
                    scroll_x: x.saturating_add(*scroll_x),
                    scroll_y: y.saturating_add(*scroll_y),
                });
                next_bg_number = next_bg_number.saturating_add(1);
            }
            AstNode::SpawnSprite {
                var_name,
                resource_name,
                x,
                y,
                priority_high,
            } => {
                let palette_slot = ast
                    .sprite_assets
                    .iter()
                    .find(|asset| asset.resource_name == *resource_name)
                    .map(|asset| asset.palette_slot)
                    .unwrap_or_default();
                let spawn = SpawnedSprite {
                    var_name: var_name.clone(),
                    sprite_index: next_sprite_index,
                    x: *x,
                    y: *y,
                    priority: if *priority_high { 3 } else { 0 },
                    tile_base: tile_base_lookup
                        .get(resource_name)
                        .copied()
                        .unwrap_or_default(),
                    palette_slot,
                };
                spawn_lookup.insert(var_name.clone(), context.spawns.len());
                context.spawns.push(spawn);
                next_sprite_index = next_sprite_index.saturating_add(1);
            }
            AstNode::SetAnimation {
                var_name,
                resource_name,
                frame_time,
                frames,
                looping,
                ..
            } => {
                let Some(spawn_index) = spawn_lookup.get(var_name).copied() else {
                    continue;
                };
                let Some(asset) = ast
                    .sprite_assets
                    .iter()
                    .find(|asset| asset.resource_name == *resource_name)
                else {
                    continue;
                };
                let spawn = &context.spawns[spawn_index];
                let frame_tiles = normalized_animation_frames(frames)
                    .into_iter()
                    .map(|frame| {
                        spawn
                            .tile_base
                            .saturating_add(frame.saturating_mul(tiles_per_frame(asset)))
                    })
                    .collect::<Vec<_>>();

                context.animations.push(AnimationState {
                    state_name: format!("{}_anim", var_name),
                    sprite_index: spawn.sprite_index,
                    x: spawn.x,
                    y: spawn.y,
                    priority: spawn.priority,
                    palette_slot: spawn.palette_slot,
                    frame_tiles,
                    frame_time: *frame_time,
                    looping: *looping,
                });
            }
            _ => {}
        }
    }

    context
}

fn render_animation_update(out: &mut String, animation: &AnimationState) {
    if animation.frame_time == 0 || animation.frame_tiles.len() <= 1 {
        return;
    }

    let last_frame = animation.frame_tiles.len() - 1;
    out.push_str(&format!(
        "        if (++{name}_timer >= {delay}) {{\n",
        name = animation.state_name,
        delay = animation.frame_time
    ));
    out.push_str(&format!("            {}_timer = 0;\n", animation.state_name));
    out.push_str(&format!(
        "            if ({}_cursor < {}) {{\n",
        animation.state_name, last_frame
    ));
    out.push_str(&format!("                {}_cursor++;\n", animation.state_name));
    out.push_str(&format!(
        "                oamSet({index}, {x}, {y}, {priority}, 0, 0, {name}_tiles[{name}_cursor], {palette});\n",
        index = animation.sprite_index,
        x = animation.x.max(0),
        y = animation.y.max(0),
        priority = animation.priority,
        name = animation.state_name,
        palette = animation.palette_slot
    ));
    out.push_str("            }");
    if animation.looping {
        out.push_str(" else {\n");
        out.push_str(&format!("                {}_cursor = 0;\n", animation.state_name));
        out.push_str(&format!(
            "                oamSet({index}, {x}, {y}, {priority}, 0, 0, {name}_tiles[{name}_cursor], {palette});\n",
            index = animation.sprite_index,
            x = animation.x.max(0),
            y = animation.y.max(0),
            priority = animation.priority,
            name = animation.state_name,
            palette = animation.palette_slot
        ));
        out.push_str("            }\n");
    } else {
        out.push('\n');
    }
    out.push_str("        }\n");
}

fn render_aabb_helper() -> &'static str {
    "static u8 retro_aabb_intersects(s16 left_x, s16 left_y, u16 left_w, u16 left_h, s16 right_x, s16 right_y, u16 right_w, u16 right_h)\n\
{\n\
    return left_x < (right_x + (s16)right_w)\n\
        && (left_x + (s16)left_w) > right_x\n\
        && left_y < (right_y + (s16)right_h)\n\
        && (left_y + (s16)left_h) > right_y;\n\
}\n"
}

fn render_collision_check(out: &mut String, check: &AabbCollisionCheck) {
    out.push_str(&format!(
        "        u8 {result_name} = retro_aabb_intersects({left_x}, {left_y}, {left_width}, {left_height}, {right_x}, {right_y}, {right_width}, {right_height});\n",
        result_name = check.result_name,
        left_x = check.left.x,
        left_y = check.left.y,
        left_width = check.left.width,
        left_height = check.left.height,
        right_x = check.right.x,
        right_y = check.right.y,
        right_width = check.right.width,
        right_height = check.right.height
    ));
    out.push_str(&format!(
        "        if ({}) {{\n            // Collision: {} <-> {}\n        }}\n",
        check.result_name, check.left.entity_id, check.right.entity_id
    ));
}

fn render_input_binding(
    out: &mut String,
    result_name: &str,
    entity_id: &str,
    action_name: &str,
    state_var: &str,
    button: &str,
) {
    let Some(button_mask) = snes_button_mask(button) else {
        out.push_str(&format!(
            "        // Unsupported input mapping on SNES: {}.{} -> {}\n",
            entity_id, action_name, button
        ));
        return;
    };

    out.push_str(&format!(
        "        u16 {result_name} = {state_var} & {button_mask};\n",
        result_name = result_name,
        state_var = state_var,
        button_mask = button_mask
    ));
    out.push_str(&format!(
        "        if ({}) {{\n            // Input: {}.{}\n        }}\n",
        result_name, entity_id, action_name
    ));
}

fn snes_joypad_port(device: &str) -> u8 {
    match device {
        "joypad_2" => 1,
        _ => 0,
    }
}

fn snes_button_mask(button: &str) -> Option<&'static str> {
    match button {
        "DPAD_UP" => Some("KEY_UP"),
        "DPAD_DOWN" => Some("KEY_DOWN"),
        "DPAD_LEFT" => Some("KEY_LEFT"),
        "DPAD_RIGHT" => Some("KEY_RIGHT"),
        "BUTTON_A" => Some("KEY_A"),
        "BUTTON_B" => Some("KEY_B"),
        "BUTTON_X" => Some("KEY_X"),
        "BUTTON_Y" => Some("KEY_Y"),
        "START" => Some("KEY_START"),
        "SELECT" => Some("KEY_SELECT"),
        _ => None,
    }
}

fn initial_tile_for_spawn(context: &SnesContext, var_name: &str) -> Option<u16> {
    context
        .animations
        .iter()
        .find(|animation| animation.state_name == format!("{}_anim", var_name))
        .and_then(|animation| animation.frame_tiles.first().copied())
}

fn tile_base_lookup(ast: &AstOutput) -> std::collections::HashMap<String, u16> {
    let mut lookup = std::collections::HashMap::new();
    let mut accumulated_tiles = 0u16;

    for asset in &ast.sprite_assets {
        lookup.insert(asset.resource_name.clone(), accumulated_tiles);
        accumulated_tiles = accumulated_tiles.saturating_add(tile_count(asset));
    }

    lookup
}

fn build_resource_manifest(ast: &AstOutput) -> String {
    let mut out = String::new();
    let tilemap_assets = collect_tilemap_assets(ast);
    out.push_str("// Generated by RetroDev Studio - DO NOT EDIT\n");
    out.push_str("// Workspace SNES asset manifest\n\n");

    if ast.sprite_assets.is_empty() && tilemap_assets.is_empty() {
        out.push_str("# no visual assets staged for this target\n");
        return out;
    }

    for asset in &tilemap_assets {
        out.push_str(&format!(
            "BMP {} <- {} ({}x{} tiles)\n",
            asset.resource_name, asset.asset_path, asset.map_width, asset.map_height
        ));
    }

    for asset in &ast.sprite_assets {
        out.push_str(&format!(
            "BMP {} <- {} ({}x{}, pal {})\n",
            asset.resource_name,
            asset.asset_path,
            asset.frame_width,
            asset.frame_height,
            asset.palette_slot
        ));
    }

    out
}

fn sprite_size_config(frame_width: u32, frame_height: u32) -> Option<SpriteSizeConfig> {
    if frame_width != frame_height {
        return None;
    }

    match frame_width {
        8 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE8_L16",
            sprite_size: "OBJ_SMALL",
        }),
        16 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE16_L32",
            sprite_size: "OBJ_SMALL",
        }),
        32 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE32_L64",
            sprite_size: "OBJ_SMALL",
        }),
        64 => Some(SpriteSizeConfig {
            oam_size: "OBJ_SIZE32_L64",
            sprite_size: "OBJ_LARGE",
        }),
        _ => None,
    }
}

fn normalized_animation_frames(frames: &[u32]) -> Vec<u16> {
    if frames.is_empty() {
        vec![0]
    } else {
        frames
            .iter()
            .map(|frame| (*frame).min(u16::MAX as u32) as u16)
            .collect()
    }
}

fn tiles_per_frame(asset: &SpriteAsset) -> u16 {
    let width_tiles = (asset.frame_width / 8).max(1);
    let height_tiles = (asset.frame_height / 8).max(1);
    (width_tiles * height_tiles).min(u16::MAX as u32) as u16
}

fn tile_count(asset: &SpriteAsset) -> u16 {
    let frame_count = asset.animation_count.max(1);
    (u32::from(tiles_per_frame(asset)) * frame_count).min(u16::MAX as u32) as u16
}

fn snes_map_size_mode(asset: &TilemapAsset) -> &'static str {
    match (asset.map_width > 32, asset.map_height > 32) {
        (false, false) => "SC_32x32",
        (true, false) => "SC_64x32",
        (false, true) => "SC_32x64",
        (true, true) => "SC_64x64",
    }
}

fn tilemap_tile_address(bg_number: u8) -> u16 {
    0x2000 + (u16::from(bg_number) * 0x1000)
}

fn tilemap_map_address(bg_number: u8) -> u16 {
    u16::from(bg_number) * 0x1000
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::ast_generator::SpriteAnimation;

    fn sprite_asset() -> SpriteAsset {
        SpriteAsset {
            resource_name: "hero".to_string(),
            asset_path: "assets/sprites/hero.png".to_string(),
            frame_width: 16,
            frame_height: 16,
            palette_slot: 0,
            animation_count: 3,
            default_animation: Some(SpriteAnimation {
                name: "walk".to_string(),
                frames: vec![0, 1, 2],
                frame_time: 6,
                looping: true,
            }),
        }
    }

    #[test]
    fn snes_emitter_generates_frame_timer_for_default_animation() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::SpriteSystemInit,
                AstNode::LoadSpritesheet {
                    resource_name: "hero".to_string(),
                    asset_path: "assets/sprites/hero.png".to_string(),
                    frame_width: 16,
                    frame_height: 16,
                    palette_slot: 0,
                },
                AstNode::SpawnSprite {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    x: 32,
                    y: 48,
                    priority_high: true,
                },
                AstNode::SetAnimation {
                    var_name: "spr_hero".to_string(),
                    resource_name: "hero".to_string(),
                    anim_index: 0,
                    frame_time: 6,
                    frames: vec![0, 1, 2],
                    looping: true,
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: vec![sprite_asset()],
        };

        let output = emit_snes(&ast, "Timing Demo");

        assert!(output
            .main_c
            .contains("static const u16 spr_hero_anim_tiles[] = {0, 4, 8};"));
        assert!(output.main_c.contains("if (++spr_hero_anim_timer >= 6)"));
        assert!(output
            .main_c
            .contains("oamSet(0, 32, 48, 3, 0, 0, spr_hero_anim_tiles[spr_hero_anim_cursor], 0);"));
    }

    #[test]
    fn snes_emitter_initializes_tilemap_backgrounds() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::LoadTilemap {
                    resource_name: "background_tilemap".to_string(),
                    asset_path: "assets/tilesets/level.ppm".to_string(),
                    map_width: 64,
                    map_height: 32,
                },
                AstNode::DrawTilemap {
                    resource_name: "background_tilemap".to_string(),
                    x: 16,
                    y: 24,
                    scroll_x: 8,
                    scroll_y: 4,
                },
                AstNode::GameLoopBegin,
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
        };

        let output = emit_snes(&ast, "Tilemap Demo");

        assert!(output.main_c.contains("#include \"background_tilemap.inc\""));
        assert!(output.main_c.contains(
            "bgInitTileSet(0, &background_tilemap_til, &background_tilemap_pal, 0, (&background_tilemap_tilend - &background_tilemap_til), (&background_tilemap_palend - &background_tilemap_pal), BG_16COLORS, 0x2000);"
        ));
        assert!(output.main_c.contains(
            "bgInitMapSet(0, (u8*)&background_tilemap_map, (&background_tilemap_mapend - &background_tilemap_map), SC_64x32, 0x0000);"
        ));
        assert!(output.main_c.contains("bgSetScroll(0, 24, 28);"));
    }

    #[test]
    fn snes_emitter_emits_manual_aabb_collision_checks() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::CheckCollisionAabb {
                    result_name: "collision_player_badnik".to_string(),
                    left: crate::compiler::ast_generator::CollisionBox {
                        entity_id: "player".to_string(),
                        x: 18,
                        y: 28,
                        width: 16,
                        height: 24,
                    },
                    right: crate::compiler::ast_generator::CollisionBox {
                        entity_id: "badnik".to_string(),
                        x: 40,
                        y: 28,
                        width: 24,
                        height: 24,
                    },
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
        };

        let output = emit_snes(&ast, "Collision Demo");

        assert!(output.main_c.contains("static u8 retro_aabb_intersects("));
        assert!(output.main_c.contains(
            "u8 collision_player_badnik = retro_aabb_intersects(18, 28, 16, 24, 40, 28, 24, 24);"
        ));
        assert!(output
            .main_c
            .contains("// Collision: player <-> badnik"));
    }

    #[test]
    fn snes_emitter_reads_input_mappings() {
        let ast = AstOutput {
            nodes: vec![
                AstNode::GameLoopBegin,
                AstNode::ReadInputDevice {
                    device: "joypad_1".to_string(),
                    state_var: "joypad_1_state".to_string(),
                },
                AstNode::MapInputAction {
                    result_name: "input_player_move_left".to_string(),
                    entity_id: "player".to_string(),
                    action_name: "move_left".to_string(),
                    state_var: "joypad_1_state".to_string(),
                    button: "DPAD_LEFT".to_string(),
                },
                AstNode::MapInputAction {
                    result_name: "input_player_jump".to_string(),
                    entity_id: "player".to_string(),
                    action_name: "jump".to_string(),
                    state_var: "joypad_1_state".to_string(),
                    button: "BUTTON_A".to_string(),
                },
                AstNode::SpriteUpdate,
                AstNode::VSync,
                AstNode::GameLoopEnd,
            ],
            sprite_assets: Vec::new(),
        };

        let output = emit_snes(&ast, "Input Demo");

        assert!(output.main_c.contains("scanPads();"));
        assert!(output
            .main_c
            .contains("u16 joypad_1_state = padsCurrent(0);"));
        assert!(output
            .main_c
            .contains("u16 input_player_move_left = joypad_1_state & KEY_LEFT;"));
        assert!(output
            .main_c
            .contains("u16 input_player_jump = joypad_1_state & KEY_A;"));
        assert!(output.main_c.contains("// Input: player.move_left"));
        assert!(output.main_c.contains("// Input: player.jump"));
    }
}
