# File generated by Qoder CLI
#!/usr/bin/env python3
"""Teste do localizador de recursos (locate-streams.py) com resposta conhecida (deterministica).

Por que este teste existe: localizar streams por tabela de ponteiros so pode
ser alegado como evidencia se o detector achar o que esta la (recall) E nao
achar o que nao esta (especificidade). Ambas as metades sao medidas aqui com
streams empacotadas pelo ORACULO externo, nunca pelo proprio coder.

ROM sintetica: cabecalho MD valido (soma conferida), tabela de ponteiros em
0x4000 com 5 entradas + terminador 0xFFFFFFFF, alvos reais (2 Nemesis +
2 Enigma empacotados pelo oraculo) e um isca de ruido pseudoaleatorio que
NAO deve ser reportada.
"""
import hashlib, importlib.util, os, resource, subprocess, sys, tempfile, zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
LOC = importlib.util.spec_from_file_location("locate_streams",
                                             os.path.join(HERE, "locate-streams.py"))
locate_streams = importlib.util.module_from_spec(LOC)
LOC.loader.exec_module(locate_streams)

NEMCMP = os.path.expanduser("~/.cache/rex-codecs/oracle-tools/bin/nemcmp")
ENICMP = os.path.expanduser("~/.cache/rex-codecs/oracle-tools/bin/enicmp")
FATOR = 1 << 13

falhas, checks = [], 0


def ok(cond, msg):
    global checks
    checks += 1
    if not cond:
        falhas.append(msg)
        print(f"  FAIL {msg}")
    return cond


def oracle(args, exe):
    def limits():
        resource.setrlimit(resource.RLIMIT_AS, (2 << 30, 2 << 30))
        resource.setrlimit(resource.RLIMIT_CPU, (25, 25))
        resource.setrlimit(resource.RLIMIT_FSIZE, (32 << 20, 32 << 20))
    p = subprocess.run([exe] + args, stdin=subprocess.DEVNULL,
                       capture_output=True, timeout=30, preexec_fn=limits)
    return p.returncode


def pack_nemesis(tmp, name, plain):
    src = os.path.join(tmp, name + ".bin")
    dst = os.path.join(tmp, name + ".nem")
    open(src, "wb").write(plain)
    rc = oracle([src, dst], NEMCMP)
    assert rc == 0 and os.path.exists(dst), f"encode nemesis rc={rc}"
    return open(dst, "rb").read()


def pack_enigma(tmp, name, words):
    src = os.path.join(tmp, name + ".bin")
    dst = os.path.join(tmp, name + ".eni")
    open(src, "wb").write(b"".join(w.to_bytes(2, "big") for w in words))
    rc = oracle([src, dst], ENICMP)
    assert rc == 0 and os.path.exists(dst), f"encode enigma rc={rc}"
    return open(dst, "rb").read()


def build_rom(streams_by_target, table_at=0x4000, size=0x80000):
    """Rom sintetica: header MD, codigo pseudoaleatorio antes da tabela."""
    data = bytearray(((i * 2654435761) >> 13) & 0xFF for i in range(size))
    data[0x100:0x110] = b"SEGA GENESIS    ".ljust(16, b" ")
    data[0x110:0x120] = b"(C)TEST 1992    "
    data[0x120:0x12C] = b"LOCATOR TEST"  # 12 bytes: 0x12C inicia o campo USA
    for tgt, blob in streams_by_target.items():
        data[tgt:tgt + len(blob)] = blob
    o = table_at
    for tgt in sorted(streams_by_target):
        data[o:o + 4] = tgt.to_bytes(4, "big")
        o += 4
    data[o:o + 4] = (0xFFFFFFFF).to_bytes(4, "big")
    data[0x1A4:0x1A8] = (size - 1).to_bytes(4, "big")
    data[0x18E:0x190] = b"\x00\x00"
    s = 0
    for off in range(0x200, size - 1, 2):
        s = (s + int.from_bytes(data[off:off + 2], "big")) & 0xFFFF
    data[0x18E:0x190] = s.to_bytes(2, "big")
    return bytes(data)


def main():
    for exe in (NEMCMP, ENICMP):
        if not os.path.exists(exe):
            print(f"SKIP: oraculo ausente {exe}")
            return 0
    tmp = tempfile.mkdtemp(prefix="loc-test-")
    nem_a = pack_nemesis(tmp, "ramp", bytes(((i * 7) & 0x0F) for i in range(4096)))
    nem_b = pack_nemesis(tmp, "blocks", bytes([0x5A, 0x33] * 2048))
    eni_a = pack_enigma(tmp, "w1", list(range(600)))
    eni_b = pack_enigma(tmp, "w2", [0x1234, 0x1235, 0x0000, 0xFFFF] * 150)

    targets = {0x10000: nem_a, 0x18000: nem_b, 0x20000: eni_a, 0x28000: eni_b}
    total = sum(len(b) for b in targets.values())
    print(f"streams empacotadas pelo oraculo: "
          f"{[(hex(t), len(b)) for t, b in targets.items()]} "
          f"total={total} de {0x80000} ({100*total/0x80000:.1f}% da ROM)")

    # --- 1) recall: o detector acha os quatro alvos ancorados pela tabela ----
    rom = build_rom(targets)
    info, runs, resources, _ = locate_streams.locate(rom, {}, min_run=4)
    achados = {int(r["ponteiro_valor"], 16): r
               for t in resources for r in t["recursos"]}
    print(f"corridas={len(runs)} tabelas={len(resources)} alvos_validados={len(achados)}")
    ok(info["internal_name"] == "LOCATOR TEST", "nome interno do header lido")
    ok(info["declared_checksum"] == info["computed_checksum_full"], "soma MD confere")
    for tgt in targets:
        r = achados.get(tgt)
        ok(r is not None, f"alvo {hex(tgt)} detectado pela tabela")
        if r:
            ok(r["bytes_consumed"] == len(targets[tgt]),
               f"bytes_consumed exato em {hex(tgt)}: {r['bytes_consumed']} vs {len(targets[tgt])}")
    codecs = sorted(r["codec"] for r in achados.values())
    ok(codecs.count("nemesis") == 2 and codecs.count("enigma") == 2,
       f"codec certo por alvo (obtido={codecs})")

    # --- 2) a ancora e obrigatoria: os mesmos bytes, sem exigencia de tabela
    #        contigua, nao podem ser reportados como recursos. ---------------
    _, _, resources2, _ = locate_streams.locate(rom, {}, min_run=10**6)
    ok(not resources2, "sem ancora de tabela, nenhuma tabela de recursos e reportada")

    # --- 3) isca: ponteiros para ruido pseudoaleatorio NAO viram recurso ----
    decoy = {0x30000: b"", 0x34000: b"", 0x38000: b"", 0x3C000: b""}
    rom3 = bytearray(build_rom({**targets}))
    o = 0x5000
    for t in sorted(decoy):
        rom3[o:o + 4] = t.to_bytes(4, "big")
        o += 4
    rom3[o:o + 4] = (0xFFFFFFFF).to_bytes(4, "big")
    _, _, resources3, _ = locate_streams.locate(bytes(rom3), {}, min_run=4)
    alvos3 = {int(r["ponteiro_valor"], 16) for t in resources3 for r in t["recursos"]}
    ok(not (alvos3 & set(decoy)), f"ruido nao reportado como recurso (obtido={sorted(hex(a) for a in alvos3)})")
    ok(set(targets) <= alvos3, "alvos verdadeiros continuam achados com a isca presente")

    # --- 4) confirmacao externa no span exato consumido ---------------------
    doc_targets = []
    for t, blob in targets.items():
        r = achados[t]
        span = rom[t:t + r["bytes_consumed"]]
        out, err = locate_streams.oracle_decode(r["codec"], span)
        ok(out is not None and hashlib.sha256(out).hexdigest() == r["output_sha256"],
           f"oraculo reproduz byte-a-byte o recurso {hex(t)} no span consumido ({err})")
        doc_targets.append((hex(t), r["codec"], r["variant"], r["output_size"]))
    print("recursos detectados:", doc_targets)

    # --- 5) encadeamento e a evidencia forte: quando a tabela fatia a regiao
    #        em streams contiguas, alvo[i]+span[i] == alvo[i+1] para todo i.
    chained = {}
    tgt = 0x30000
    for nome, blob in (("c1", nem_a), ("c2", nem_b), ("c3", eni_a), ("c4", eni_b)):
        chained[tgt] = blob
        tgt += len(blob)
    rom5 = build_rom(chained, table_at=0x7000)
    _, _, res5, _ = locate_streams.locate(rom5, {}, min_run=4)
    t5 = [t for t in res5 if t["tabela_offset"] == "0x7000"]
    ok(len(t5) == 1, f"tabela da cadeia encontrada ({len(t5)})")
    if t5:
        ok(t5[0]["elinks_encadeados"] == len(chained) - 1,
           f"elinks = alvos-1 (obtido {t5[0]['elinks_encadeados']} de {len(chained)-1})")
        ok(t5[0]["confianca"] == "alta", f"confianca alta ({t5[0]['confianca']})")
    # a mesma cadeia com lacunas de 8 bytes (preserva o alinhamento de palavra
    # que o detector exige) nao deve alegar cadeia cheia
    gapT = {}
    g = 0x30000
    for blob in chained.values():
        gapT[g] = blob
        g += len(blob) + 8
    rom5b = build_rom(gapT, table_at=0x7000)
    _, _, res5b, _ = locate_streams.locate(rom5b, {}, min_run=4)
    t5b = [t for t in res5b if t["tabela_offset"] == "0x7000"]
    ok(t5b and t5b[0]["elinks_encadeados"] == 0 and t5b[0]["confianca"] != "alta",
       f"lacunas entre streams impedem alegacao de cadeia "
       f"(obtido={None if not t5b else t5b[0]['elinks_encadeados']})")
    # alvo impar (offset 0x30717) e excluido pelo detector: alinhamento de
    # palavra 68k e hipotese assumida, entao fica registrada como tal.
    rom_odd = build_rom({0x30000: nem_a, 0x30717: nem_b, 0x30800: eni_a, 0x30900: eni_b},
                        table_at=0x7000)
    _, _, res_odd, _ = locate_streams.locate(rom_odd, {}, min_run=4)
    ok(not [t for t in res_odd if t["tabela_offset"] == "0x7000"],
       "alvo impar derruba a corrida (limite do detector registrado)")

    # --- 6) run com ponteiros repetidos NAO e tabela (preenchimento constante)
    rom6 = bytearray(build_rom(dict(targets)))
    o = 0x6000
    for _ in range(6):
        rom6[o:o + 4] = (0x10000).to_bytes(4, "big")
        o += 4
    rom6[o:o + 4] = (0xFFFFFFFF).to_bytes(4, "big")
    _, _, res6, _ = locate_streams.locate(bytes(rom6), {}, min_run=4)
    alvos6 = [r for t in res6 for r in t["recursos"] if t["tabela_offset"] == "0x6000"]
    ok(not alvos6, f"ponteiros repetidos nao formam tabela ({len(alvos6)} recursos)")

    print(f"\n{checks - len(falhas)}/{checks} verificacoes passaram")
    if falhas:
        print("FALHAS:")
        for f in falhas:
            print(" -", f)
        return 1
    print("OK")
    return 0

if __name__ == "__main__":
    sys.exit(main())
