/**
 * nodeCompiler.ts — Conversor bidirecional NodeGraph ↔ C (Fase 3)
 *
 * Node → C:  percorre o grafo a partir dos nós "event_start", segue arestas exec
 *            e emite código C equivalente para SGDK/PVSnesLib.
 *
 * C → Node:  parse básico de main.c gerado (SPR_addSprite, oamSet, parallax calls)
 *            e reconstrói nós correspondentes.
 */

import type { NodeGraph, GraphNode, NodeEdge } from "../../components/nodegraph/NodeGraphEditor";

// ── Node → C ─────────────────────────────────────────────────────────────────

function resolveExecChain(startNode: GraphNode, graph: NodeGraph): GraphNode[] {
  const chain: GraphNode[] = [startNode];
  const visited = new Set<string>([startNode.id]);
  let current = startNode;

  while (true) {
    const outEdge = graph.edges.find(
      (e: NodeEdge) => e.fromNode === current.id && e.fromPort === "exec"
    );
    if (!outEdge) break;
    const next = graph.nodes.find((n: GraphNode) => n.id === outEdge.toNode);
    if (!next || visited.has(next.id)) break;
    visited.add(next.id);
    chain.push(next);
    current = next;
  }

  return chain;
}

function emitNodeC(node: GraphNode, target: "megadrive" | "snes"): string {
  const p = node.params;

  switch (node.type) {
    case "event_start":
      return "    // [On Start]\n";

    case "sprite_move":
      if (target === "snes") {
        return `    // Move ${p.target}: oamSet with dx=${p.dx}, dy=${p.dy} (update OAM manually)\n`;
      }
      return `    SPR_setPosition(spr_${p.target}, SPR_getX(spr_${p.target}) + ${p.dx}, SPR_getY(spr_${p.target}) + ${p.dy});\n`;

    case "sprite_anim":
      if (target === "snes") {
        return `    // Set anim '${p.anim}' on ${p.target} (update tile index manually)\n`;
      }
      return `    SPR_setAnim(spr_${p.target}, ANIM_${String(p.anim).toUpperCase()});\n`;

    case "condition_overlap":
      return `    if (SPR_overlaps(spr_${p.a}, spr_${p.b})) {\n        // [overlap branch]\n    }\n`;

    case "effect_parallax":
      if (target === "snes") {
        // PVSnesLib: bgSetScroll(u8 bgIndex, u16 x, u16 y)
        return `    bg_scroll_${p.layer} += ${p.speed_x}; bgSetScroll(${p.layer}, bg_scroll_${p.layer}, 0);\n`;
      }
      return `    VDP_setHorizontalScroll(BG_${p.layer}, bg_scroll_${p.layer} += ${p.speed_x});\n`;

    case "effect_raster": {
      const scanline = Number(p.scanline);
      const offset   = Number(p.offset_x);
      if (target === "snes") {
        // PVSnesLib: bgSetScroll com verificação de scanline via irq/hdma (simplificado)
        return `    if (snes_vblank_count == ${scanline}) { bgSetScroll(0, ${offset}, 0); }\n`;
      }
      return `    VDP_setHorizontalScrollLine(BG_A, ${scanline}, ${offset});\n`;
    }

    case "logic_and":
      return `    // [AND gate — combine boolean conditions]\n`;

    case "action_sound":
      if (target === "snes") {
        return `    SPC_playSFX(SFX_${String(p.sfx).toUpperCase()});\n`;
      }
      return `    SND_startPlayPCM(SFX_${String(p.sfx).toUpperCase()}, 1, SOUND_PCM_CH_AUTO);\n`;

    default:
      return `    // [unknown node: ${node.type}]\n`;
  }
}

/**
 * Compila um NodeGraph para código C.
 * Percorre todas as chains exec a partir de nós "event_start".
 */
export function compileGraphToC(
  graph: NodeGraph,
  projectName: string,
  target: "megadrive" | "snes" = "megadrive"
): string {
  const include = target === "snes" ? "#include <snes.h>" : "#include <genesis.h>";
  let out = `// Generated by RetroDev Studio NodeGraph — DO NOT EDIT\n// Project: ${projectName}\n\n${include}\n#include "resources.h"\n\n`;

  const startNodes = graph.nodes.filter((n: GraphNode) => n.type === "event_start");

  if (startNodes.length === 0) {
    return out + "// No event_start node found in graph.\n";
  }

  // Collect sprite var declarations
  const spriteNodes = graph.nodes.filter(
    (n: GraphNode) => n.type === "sprite_move" || n.type === "sprite_anim"
  );
  const spriteVars = new Set<string>(
    spriteNodes.map((n: GraphNode) => String(n.params.target))
  );

  if (target === "megadrive") {
    spriteVars.forEach((v) => { out += `static Sprite* spr_${v};\n`; });
  } else {
    spriteVars.forEach((v) => { out += `static u16 oam_${v};\n`; });
  }

  out += "\nint main() {\n";

  for (const startNode of startNodes) {
    const chain = resolveExecChain(startNode, graph);
    for (const node of chain) {
      out += emitNodeC(node, target);
    }
  }

  if (target === "snes") {
    out += "\n    while (true) {\n        oamUpdate();\n        WaitForVBlank();\n    }\n";
  } else {
    out += "\n    while (TRUE) {\n        SPR_update();\n        SYS_doVBlankProcess();\n    }\n";
  }

  out += "\n    return 0;\n}\n";
  return out;
}

// ── C → Node (basic round-trip parser) ───────────────────────────────────────

import type { NodeType } from "../../components/nodegraph/NodeGraphEditor";

interface ParsedNode {
  type: NodeType;
  params: Record<string, string | number>;
}

/**
 * Parseia um main.c gerado pelo Studio e reconstrói uma lista de nós.
 * Suporta apenas os patterns emitidos pelo próprio Studio (round-trip).
 */
export function parseCToNodes(source: string): ParsedNode[] {
  const nodes: ParsedNode[] = [];

  // Sempre começa com event_start
  nodes.push({ type: "event_start", params: {} });

  const lines = source.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    // SPR_setPosition → sprite_move
    // Regex não-guloso para capturar corretamente dx e dy, incluindo valores negativos
    const moveMatch = trimmed.match(/SPR_setPosition\(spr_(\w+),\s*\S+\s*\+\s*(-?\d+),\s*\S+\s*\+\s*(-?\d+)/);
    if (moveMatch) {
      nodes.push({ type: "sprite_move", params: { target: moveMatch[1], dx: Number(moveMatch[2]), dy: Number(moveMatch[3]) } });
      continue;
    }

    // SPR_setAnim → sprite_anim
    const animMatch = trimmed.match(/SPR_setAnim\(spr_(\w+),\s*ANIM_(\w+)\)/);
    if (animMatch) {
      nodes.push({ type: "sprite_anim", params: { target: animMatch[1], anim: animMatch[2].toLowerCase() } });
      continue;
    }

    // VDP_setHorizontalScroll → effect_parallax (Mega Drive)
    const parallaxMatch = trimmed.match(/VDP_setHorizontalScroll\(BG_(\w+),.*\+= (-?\d+)\)/);
    if (parallaxMatch) {
      nodes.push({ type: "effect_parallax", params: { layer: parallaxMatch[1], speed_x: Number(parallaxMatch[2]), speed_y: 0 } });
      continue;
    }

    // bgSetScroll → effect_parallax (SNES / PVSnesLib)
    const snesParallaxMatch = trimmed.match(/bg_scroll_(\w+) \+= (-?\d+); bgSetScroll\(/);
    if (snesParallaxMatch) {
      nodes.push({ type: "effect_parallax", params: { layer: snesParallaxMatch[1], speed_x: Number(snesParallaxMatch[2]), speed_y: 0 } });
      continue;
    }

    // VDP_setHorizontalScrollLine → effect_raster (Mega Drive)
    const rasterMatch = trimmed.match(/VDP_setHorizontalScrollLine\(BG_\w+,\s*(\d+),\s*(-?\d+)\)/);
    if (rasterMatch) {
      nodes.push({ type: "effect_raster", params: { scanline: Number(rasterMatch[1]), offset_x: Number(rasterMatch[2]) } });
      continue;
    }

    // SND_startPlayPCM → action_sound (Mega Drive)
    const soundMatch = trimmed.match(/SND_startPlayPCM\(SFX_(\w+)/);
    if (soundMatch) {
      nodes.push({ type: "action_sound", params: { sfx: soundMatch[1].toLowerCase() } });
      continue;
    }

    // SPC_playSFX → action_sound (SNES / PVSnesLib)
    const snesSoundMatch = trimmed.match(/SPC_playSFX\(SFX_(\w+)/);
    if (snesSoundMatch) {
      nodes.push({ type: "action_sound", params: { sfx: snesSoundMatch[1].toLowerCase() } });
      continue;
    }
  }

  return nodes;
}
